import {
	DEFAULT_ZHIPU_CHAT_MODEL,
	DEFAULT_ZHIPU_IMAGE_MODEL,
	DEFAULT_ZHIPU_LAYOUT_MODEL,
	DEFAULT_ZHIPU_SPEECH_MODEL,
	DEFAULT_ZHIPU_TOKENIZER_MODEL,
	DEFAULT_ZHIPU_VIDEO_MODEL,
} from '../constants'
import type { ProviderDescriptor } from '../provider/contracts'

export const zhipuProviderDescriptor: ProviderDescriptor = {
	id: 'zhipu',
	label: 'Zhipu OpenAPI',
	pluginId: 'ZhipuProviderPlugin',
	operations: [
		{
			id: 'ocr.layout_parsing',
			label: 'GLM OCR layout parsing',
			path: '/layout_parsing',
			method: 'POST',
			defaultModel: DEFAULT_ZHIPU_LAYOUT_MODEL,
			unitName: 'request',
		},
		{
			id: 'ocr.files',
			label: 'Files OCR',
			path: '/files/ocr',
			method: 'POST',
			unitName: 'request',
		},
		{
			id: 'chat.completions',
			label: 'Chat completions',
			path: '/chat/completions',
			method: 'POST',
			defaultModel: DEFAULT_ZHIPU_CHAT_MODEL,
			unitName: 'token',
		},
		{
			id: 'tokenizer',
			label: 'Text tokenizer',
			path: '/tokenizer',
			method: 'POST',
			defaultModel: DEFAULT_ZHIPU_TOKENIZER_MODEL,
			unitName: 'token',
		},
		{
			id: 'images.generations',
			label: 'Image generations',
			path: '/images/generations',
			method: 'POST',
			defaultModel: DEFAULT_ZHIPU_IMAGE_MODEL,
			unitName: 'image',
		},
		{
			id: 'images.generations.async',
			label: 'Async image generations',
			path: '/async/images/generations',
			method: 'POST',
			defaultModel: DEFAULT_ZHIPU_IMAGE_MODEL,
			unitName: 'request',
		},
		{
			id: 'async_result',
			label: 'Async result',
			path: '/async-result/{id}',
			method: 'GET',
			unitName: 'request',
		},
		{
			id: 'videos.generations',
			label: 'Video generations',
			path: '/videos/generations',
			method: 'POST',
			defaultModel: DEFAULT_ZHIPU_VIDEO_MODEL,
			unitName: 'video',
		},
		{
			id: 'audio.transcriptions',
			label: 'Audio transcriptions',
			path: '/audio/transcriptions',
			method: 'POST',
			defaultModel: DEFAULT_ZHIPU_SPEECH_MODEL,
			unitName: 'request',
		},
		{
			id: 'files.upload',
			label: 'Files upload',
			path: '/files',
			method: 'POST',
			unitName: 'request',
		},
		{
			id: 'embeddings.create',
			label: 'Embeddings',
			path: '/embeddings',
			method: 'POST',
			unitName: 'token',
		},
		{
			id: 'rerank.create',
			label: 'Rerank',
			path: '/rerank',
			method: 'POST',
			unitName: 'request',
		},
		{
			id: 'reader',
			label: 'Reader',
			path: '/reader',
			method: 'POST',
			unitName: 'request',
		},
		{
			id: 'moderations.create',
			label: 'Moderations',
			path: '/moderations',
			method: 'POST',
			unitName: 'request',
		},
		{
			id: 'web_search',
			label: 'Web search',
			path: '/web_search',
			method: 'POST',
			unitName: 'request',
		},
		{
			id: 'agents.create',
			label: 'Agents',
			path: '/v1/agents',
			method: 'POST',
			unitName: 'request',
		},
		{
			id: 'agents.async_result',
			label: 'Agent async result',
			path: '/v1/agents/async-result',
			method: 'POST',
			unitName: 'request',
		},
		{
			id: 'agents.conversation',
			label: 'Agent conversation',
			path: '/v1/agents/conversation',
			method: 'POST',
			unitName: 'request',
		},
	],
}
