import type { Context, PluginConstructor } from '@pluxel/core'
import { genObjectFromRawEntries, genObjectFromValues } from 'knitwork'

type Row = {
	name: string
	moduleId: string
	exportKey: string
	alias: string
}

export type SnapshotSourceDeps = {
	ctx: Pick<Context, 'configService'>
	entries: Iterable<[name: string, ctor: PluginConstructor]>
	isRunning(target: PluginConstructor | string): boolean
	findModuleId(name: string, ctor: PluginConstructor): string | null
	getExportKey(name: string): string | undefined
	now?: Date
	generatedBy?: string
}

export function buildSnapshotSource(deps: SnapshotSourceDeps): string {
	const now = deps.now ?? new Date()
	const generatedBy = deps.generatedBy ?? 'SnapshotPlugin'

	const rows: Row[] = []
	for (const [name, ctor] of deps.entries) {
		if (!deps.isRunning(ctor)) continue
		const moduleId = deps.findModuleId(name, ctor)
		const exportKey = deps.getExportKey(name)
		if (!moduleId || !exportKey) continue
		rows.push({ name, moduleId, exportKey, alias: aliasFor(name) })
	}

	rows.sort((a, b) =>
		a.name === b.name ? a.moduleId.localeCompare(b.moduleId) : a.name.localeCompare(b.name),
	)

	const used = new Set<string>()
	for (const r of rows) {
		const alias = r.alias
		if (!used.has(alias)) {
			used.add(alias)
			continue
		}

		const withFile = `${alias}__${basenameFor(r.moduleId)}`
		if (!used.has(withFile)) {
			used.add(withFile)
			r.alias = withFile
			continue
		}

		const keySuffix = r.exportKey === 'default' ? 'default' : safeIdent(r.exportKey)
		const withKey = `${withFile}__${keySuffix}`
		if (!used.has(withKey)) {
			used.add(withKey)
			r.alias = withKey
			continue
		}

		let i = 2
		while (used.has(`${withKey}__${i}`)) i++
		const finalAlias = `${withKey}__${i}`
		used.add(finalAlias)
		r.alias = finalAlias
	}

	const header =
		`// @generated by ${generatedBy}.buildSnapshot\n` +
		`// ${now.toISOString()}\n` +
		'/* eslint-disable */\n'

	const grouped = new Map<string, Row[]>()
	for (const r of rows) {
		const list = grouped.get(r.moduleId) ?? []
		list.push(r)
		grouped.set(r.moduleId, list)
	}

	const importLines: string[] = []
	const exportAliases = new Set<string>()
	for (const [moduleId, list] of grouped) {
		const defaultItem = list.find((e) => e.exportKey === 'default')
		const namedItems = list.filter((e) => e.exportKey !== 'default')
		if (defaultItem && namedItems.length > 0) {
			const namedPart = namedItems.map((e) => `${e.exportKey} as ${e.alias}`).join(', ')
			importLines.push(
				`import ${defaultItem.alias}, { ${namedPart} } from ${JSON.stringify(moduleId)};`,
			)
		} else if (defaultItem) {
			importLines.push(`import ${defaultItem.alias} from ${JSON.stringify(moduleId)};`)
		} else if (namedItems.length > 0) {
			const namedPart = namedItems.map((e) => `${e.exportKey} as ${e.alias}`).join(', ')
			importLines.push(`import { ${namedPart} } from ${JSON.stringify(moduleId)};`)
		}

		for (const e of list) exportAliases.add(e.alias)
	}

	const entries: [string, string][] = rows.map((r) => {
		const configRecord = deps.ctx.configService.getRawConfig(r.name)
		const cfg = genObjectFromValues(stripUndef(configRecord))
		const valCode = `{ ctor: ${r.alias}, config: ${cfg} }`
		return [r.name, valCode]
	})
	const registryCode = genObjectFromRawEntries(entries)

	const exportLine = `export { ${[...exportAliases].join(', ')} };`
	const body =
		`export const registry = ${registryCode} as const;\n\n` +
		`export type PluginName = keyof typeof registry;\n`

	return [header, ...importLines, '', exportLine, '', body].join('\n')
}

function aliasFor(name: string): string {
	let id = 'P_' + name.replace(/[^A-Za-z0-9_$]/g, '_')
	if (/^[0-9]/.test(id)) id = '_' + id
	return id
}

function basenameFor(path: string): string {
	const normalized = path.replace(/\\/g, '/')
	const last = normalized.split('/').pop() || ''
	const stem = last.replace(/\.[A-Za-z0-9]+$/, '')
	return safeIdent(stem)
}

function safeIdent(s: string): string {
	let id = s.replace(/[^A-Za-z0-9_$]/g, '_')
	if (/^[0-9]/.test(id)) id = '_' + id
	return id
}

function stripUndef<T>(obj: T): T {
	if (obj == null || typeof obj !== 'object') return obj
	if (Array.isArray(obj)) return obj.map(stripUndef) as unknown as T
	const out: Record<string, unknown> = {}
	for (const [k, v] of Object.entries(obj as Record<string, unknown>)) {
		if (v === undefined) continue
		out[k] = stripUndef(v)
	}
	return out as T
}
