export type SnapshotMainSourceOptions = {
	now?: Date
	generatedBy?: string
	configImportPath?: string
}

export function buildSnapshotMainSource(opts: SnapshotMainSourceOptions = {}): string {
	const now = opts.now ?? new Date()
	const generatedBy = opts.generatedBy ?? 'SnapshotPlugin'
	const configImportPath = opts.configImportPath ?? './snapshot.config'

	const header =
		`// @generated by ${generatedBy}.buildMain\n` +
		`// ${now.toISOString()}\n` +
		'/* eslint-disable */\n'

	// Keep this file intentionally tiny: it should be safe to bundle for "prod-like" runs.
	return (
		header +
		[
			`import { configure, getConfig } from ${JSON.stringify('@logtape/logtape')};`,
			`import { createPluxelLogtapeConfig } from ${JSON.stringify('@pluxel/core/logger')};`,
			`import { Context } from ${JSON.stringify('@pluxel/core')};`,
			`import ${JSON.stringify('@pluxel/core/services')};`,
			`import { registry } from ${JSON.stringify(configImportPath)};`,
			'',
			'// Ensure a default LogTape config exists (console sink only).',
			'if (!getConfig()) {',
			"\tawait configure(createPluxelLogtapeConfig({ preset: 'core' }));",
			'}',
			'',
			'const ctx = new Context({ name: "snapshot" });',
			'',
			'// Apply raw configs before plugin validation/start.',
			'await ctx.configService.ready;',
			'ctx.configService.batch(() => {',
			'\tfor (const [name, entry] of Object.entries(registry)) {',
			'\t\tctx.configService.patchConfig(name, entry.config as any);',
			'\t}',
			'});',
			'',
			'for (const entry of Object.values(registry)) {',
			'\tctx.registry.register(entry.ctor);',
			'}',
			'',
			'const res = await ctx.registry.commitStrict();',
			'if (!res.ok) throw res.err;',
			'ctx.logger.info`Snapshot runtime ready`;',
			'',
		].join('\n')
	)
}
