import { defineConfig } from 'tsdown'
export default defineConfig({
	entry: {
		'internal/http': 'src/http-internal.ts',
		http: 'src/http.ts',
		'internal/host-options': 'src/host-options.ts',
		service: 'src/service.ts',
		'internal/platform-host': 'src/platform-host.ts',
		'internal/api/usecases/pluginStatus': 'src/api/usecases/pluginStatus.ts',
		'internal/api/usecases/logs': 'src/api/usecases/logs.ts',
		'internal/api/usecases/pluginConfig': 'src/api/usecases/pluginConfig.ts',
		'internal/api/usecases/pluginForks': 'src/api/usecases/pluginForks.ts',
		'internal/api/usecases/pluginDependencies': 'src/api/usecases/pluginDependencies.ts',
		'internal/api/usecases/logsLlm': 'src/api/usecases/logsLlm.ts',
		'internal/api/usecases/pluginDependencyGraph': 'src/api/usecases/pluginDependencyGraph.ts',
		'internal/api/usecases/plugins': 'src/api/usecases/plugins.ts',
		'internal/api/features/pluginCatalog/service': 'src/api/features/pluginCatalog/service.ts',
		'internal/api/features/plugins/catalog-projection':
			'src/api/features/plugins/catalog-projection.ts',
		'internal/api/presenters/pluginApplyReport': 'src/api/presenters/pluginApplyReport.ts',
		'internal/services/management/log-transport': 'src/services/management/log-transport.ts',
		'internal/services/management/PluginCatalogLayoutService':
			'src/services/management/PluginCatalogLayoutService.ts',
		'internal/services/management/RuntimeManagementTarget':
			'src/services/management/RuntimeManagementTarget.ts',
		'internal/services/management/catalog-groups': 'src/services/management/catalog-groups.ts',
		'internal/services/RuntimeManagementService': 'src/services/RuntimeManagementService.ts',
		'internal/services/http/InternalApiValidationService':
			'src/services/http/InternalApiValidationService.ts',

		access: 'src/access.ts',
		'internal/config-presentation': 'src/api/presenters/configPresentation.ts',
		index: 'src/index.ts',
		client: 'src/client.ts',
		protocol: 'src/protocol.ts',
		react: 'src/react.ts',
		session: 'src/web/session/index.ts',
		endpoint: 'src/index.ts',
		product: 'src/product-contract.ts',
		'internal/web/client': 'src/web/client.ts',
		'internal/web/logs': 'src/web/logs.ts',
		'internal/web/management-validation': 'src/web/management-validation.ts',
		'internal/web/validation': 'src/web/validation.ts',
		'internal/web/utils': 'src/web/utils.ts',
		'internal/web/protocol': 'src/web/protocol.ts',
		'internal/web/security': 'src/web/security.ts',
		'internal/web/paths': 'src/web/paths.ts',
		'internal/web/react': 'src/web/react.tsx',
		'internal/web/management-target': 'src/web/management-target.ts',
		'internal/web/session/client': 'src/web/session/client.ts',
		'internal/web/session/index': 'src/web/session/index.ts',
		'internal/web/session/limits': 'src/web/session/limits.ts',
		'internal/web/session/server': 'src/web/session/server.ts',
		'internal/web/session/elysia-websocket': 'src/web/session/elysia-websocket.ts',
		'internal/web/session/protocol': 'src/web/session/protocol.ts',
		'internal/web/session/ingress': 'src/web/session/ingress.ts',
		'internal/web/session/endpoint': 'src/web/session/endpoint.ts',
		'internal/services/admin-access/AdminAccessService':
			'src/services/admin-access/AdminAccessService.ts',
		'internal/services/admin-access/types': 'src/services/admin-access/types.ts',
		'internal/services/admin-access/transport': 'src/services/admin-access/transport.ts',
		'internal/services/admin-access/response-lifetime':
			'src/services/admin-access/response-lifetime.ts',
		'internal/services/admin-access/ManagementAccessService':
			'src/services/admin-access/ManagementAccessService.ts',
		'internal/product-contract': 'src/product-contract.ts',
		'internal/validation': 'src/web/validation.ts',
		'internal/management-validation': 'src/web/management-validation.ts',
		'internal/access-types': 'src/services/admin-access/types.ts',
	},
	dts: true,
	format: ['esm'],
	clean: true,
	sourcemap: true,
})
