packages:
  - packages/*
  - plugins/*
  - vendor/gqlens/packages/codegen
  - vendor/gqlens/packages/core
  - vendor/gqlens/packages/react
  - vendor/gqlens/packages/vite
  - vendor/split-like-vscode/packages/core
  - vendor/split-like-vscode/packages/react
  - projects/*
  - projects/*/packages/*
  - projects/*/plugins/*

catalog:
  '@mantine/core': ^9.4.1
  '@mantine/dates': ^9.4.1
  '@mantine/hooks': ^9.4.1
  '@mantine/modals': ^9.4.1
  '@mantine/notifications': ^9.4.1
  '@pluxel/market': ^0.1.0
  '@tabler/icons-react': ^3.37.1
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  drizzle-orm: ^0.45.2
  react: ^19.2.7
  react-dom: ^19.2.7
  redis: ^6.1.0
  tsdown: ^0.22.5
  typescript: ^6.0.3
  undici: ^7.16.0
  vitest: ^4.1.10
  wretch: ^3.0.9

managePackageManagerVersions: false

packageExtensions:
  '@mantine/hooks@9.4.1':
    peerDependencies:
      react-dom: ^19.2.0

allowBuilds:
  '@parcel/watcher': false
  better-sqlite3: false
  esbuild: false

minimumReleaseAgeExclude:
  - '@gqlens/codegen@0.2.0'
  - '@gqlens/core@0.2.0'
  - '@gqlens/react@0.2.0'
  - '@gqlens/vite@0.2.0'

onlyBuiltDependencies:
  - esbuild

public-hoist-pattern:
  - react
  - react-dom
  - '@tabler/icons-react'
  - '@mantine/core'
  - '@mantine/hooks'
  - '@mantine/dates'
  - '@mantine/modals'
  - '@mantine/notifications'
  - tsdown

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200
