packages:
  - packages/*
  - packages/plugins/*

allowBuilds:
  '@parcel/watcher': false
  esbuild: false

onlyBuiltDependencies:
  - esbuild

public-hoist-pattern:
  - react
  - react-dom
  - '@tabler/icons-react'
  - '@mantine/core'
  - '@mantine/hooks'
  - '@mantine/dates'
  - '@mantine/modals'
  - '@mantine/notifications'
  - tsdown

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200
