import { defineConfig } from 'tsdown'

export default defineConfig({
	exports: { devExports: '@pluxel/source' },
	deps: { neverBundle: ['#pluxel/database-driver/pglite', '#pluxel/database-driver/postgres'] },
	entry: {
		vite: './src/vite.ts',
		'http/vite': './src/http-vite.ts',
		'node/vite': './src/node-vite.ts',
		'internal/vite-node-carrier': './src/development/vite-node-carrier.ts',

		index: './src/index.ts',
		build: './src/build.ts',
		'http/application': './src/http/application.ts',
		'http/listener': './src/http/listener.ts',
		'http/assets': './src/http/assets.ts',
		'database/pglite': './src/database/pglite.ts',
		'database/postgres': './src/database/postgres.ts',
		database: './src/database.ts',
		'internal/database': './src/database/internal.ts',
		'internal/database/pglite': './src/database/adapters/pglite.ts',
		'internal/database/postgres': './src/database/adapters/postgres.ts',
		http: './src/http.ts',
		'http/node': './src/http/node.ts',
		'internal/http': './src/http/internal.ts',
		node: './src/node.ts',
		workers: './src/workers.ts',
		'internal/node': './src/node/internal.ts',
		'internal/node-declaration': './src/node/declaration.ts',
		commands: './src/commands.ts',
		persistence: './src/persistence.ts',
		vault: './src/vault.ts',
		'internal/persistence': './src/persistence/service.ts',
		'internal/vault': './src/vault/service.ts',
		'internal/vault-types': './src/vault/types.ts',
		'internal/security': './src/internal/security.ts',
		'internal/workspace-fs': './src/internal/workspace-fs.ts',
		'internal/plugin-address': './src/internal/plugin-address.ts',
		'internal/owner-view': './src/internal/owner-view.ts',
	},
	format: ['esm'],
	dts: { eager: true },
	clean: true,
	treeshake: true,
})
