import { readFileSync, writeFileSync } from 'node:fs'
import ts from 'typescript'

const packageRoot = new URL('../', import.meta.url)
const methodsPath = new URL('./node_modules/@gramio/types/out/methods.d.ts', packageRoot)
const packagePath = new URL('./node_modules/@gramio/types/package.json', packageRoot)
const outputPath = new URL('./src/api/endpoints.txt', packageRoot)
const reserved = new Set(['$', 'call', 'constructor', 'events', 'id', 'request'])

const sourceText = readFileSync(methodsPath, 'utf8')
const source = ts.createSourceFile(
	methodsPath.pathname,
	sourceText,
	ts.ScriptTarget.Latest,
	true,
	ts.ScriptKind.TS,
)
const declaration = source.statements.find(
	(statement): statement is ts.InterfaceDeclaration =>
		ts.isInterfaceDeclaration(statement) && statement.name.text === 'APIMethods',
)
if (!declaration) throw new Error('@gramio/types does not export an APIMethods interface')

const methods = declaration.members.map((member) => {
	if (!member.name) throw new Error('APIMethods contains an unnamed member')
	const name = propertyName(member.name, source)
	if (!name || !/^[A-Za-z_$][\w$]*$/.test(name))
		throw new Error(`Invalid Telegram API method name: ${JSON.stringify(name)}`)
	if (reserved.has(name)) throw new Error(`Telegram API method conflicts with Bot member: ${name}`)
	return name
})
if (new Set(methods).size !== methods.length)
	throw new Error('APIMethods contains duplicate methods')

const version = (JSON.parse(readFileSync(packagePath, 'utf8')) as { version: string }).version
const generated = [
	`# Generated by scripts/generate-api.ts from @gramio/types@${version} APIMethods.`,
	'# Do not edit by hand. Read-only get* methods use GET; all other methods use POST.',
	...methods.map((name) => `${name} ${name.startsWith('get') ? 'GET' : 'POST'}`),
	'',
].join('\n')

if (process.argv.includes('--check')) {
	const current = readFileSync(outputPath, 'utf8')
	if (current !== generated) {
		const line = firstDifferentLine(current, generated)
		throw new Error(
			`Telegram API inventory is stale at line ${line}. Run pnpm api:generate and review the diff.`,
		)
	}
} else {
	writeFileSync(outputPath, generated)
}

function propertyName(name: ts.PropertyName, sourceFile: ts.SourceFile): string {
	if (ts.isIdentifier(name) || ts.isStringLiteral(name) || ts.isNumericLiteral(name))
		return name.text
	return name.getText(sourceFile)
}

function firstDifferentLine(left: string, right: string): number {
	const leftLines = left.split('\n')
	const rightLines = right.split('\n')
	const count = Math.max(leftLines.length, rightLines.length)
	for (let index = 0; index < count; index++)
		if (leftLines[index] !== rightLines[index]) return index + 1
	return count
}
