import { readFileSync, writeFileSync } from 'node:fs'
import ts from 'typescript'

const packageRoot = new URL('../', import.meta.url)
const methodsPath = new URL('./node_modules/@gramio/types/out/methods.d.ts', packageRoot)
const objectsPath = new URL('./node_modules/@gramio/types/out/objects.d.ts', packageRoot)
const packagePath = new URL('./node_modules/@gramio/types/package.json', packageRoot)
const endpointsOutputPath = new URL('./src/api/endpoints.txt', packageRoot)
const updatesOutputPath = new URL('./src/api/updates.txt', packageRoot)
const reserved = new Set([
	...Object.getOwnPropertyNames(Object.prototype),
	'$',
	'call',
	'events',
	'id',
	'request',
	'selfInfo',
	'then',
])

const source = parseSource(methodsPath)
const declaration = requireInterface(source, 'APIMethods')

const methods = declaration.members.map((member) => {
	if (!member.name) throw new Error('APIMethods contains an unnamed member')
	const name = propertyName(member.name, source)
	if (!name || !/^[A-Za-z_$][\w$]*$/.test(name))
		throw new Error(`Invalid Telegram API method name: ${JSON.stringify(name)}`)
	if (reserved.has(name)) throw new Error(`Telegram API method conflicts with Bot member: ${name}`)
	return name
})
if (new Set(methods).size !== methods.length)
	throw new Error('APIMethods contains duplicate methods')

const version = (JSON.parse(readFileSync(packagePath, 'utf8')) as { version: string }).version
const generatedEndpoints = [
	`# Generated by scripts/generate-api.ts from @gramio/types@${version} APIMethods.`,
	'# Do not edit by hand. Read-only get* methods use GET; all other methods use POST.',
	...methods.map((name) => `${name} ${name.startsWith('get') ? 'GET' : 'POST'}`),
	'',
].join('\n')

const objectsSource = parseSource(objectsPath)
const updateDeclaration = requireInterface(objectsSource, 'TelegramUpdate')
const updateKeys = updateDeclaration.members
	.map((member) => {
		if (!member.name) throw new Error('TelegramUpdate contains an unnamed member')
		return propertyName(member.name, objectsSource)
	})
	.filter((name) => name !== 'update_id')
for (const key of updateKeys) {
	if (!/^[a-z][a-z0-9_]*$/.test(key))
		throw new Error(`Invalid Telegram update field: ${JSON.stringify(key)}`)
}
if (new Set(updateKeys).size !== updateKeys.length)
	throw new Error('TelegramUpdate contains duplicate fields')
const generatedUpdates = [
	`# Generated by scripts/generate-api.ts from @gramio/types@${version} TelegramUpdate.`,
	'# Do not edit by hand. Field names intentionally follow the native Bot API payload.',
	...updateKeys,
	'',
].join('\n')

if (process.argv.includes('--check')) {
	assertCurrent(endpointsOutputPath, generatedEndpoints, 'API endpoint')
	assertCurrent(updatesOutputPath, generatedUpdates, 'update field')
} else {
	writeFileSync(endpointsOutputPath, generatedEndpoints)
	writeFileSync(updatesOutputPath, generatedUpdates)
}

function parseSource(path: URL): ts.SourceFile {
	return ts.createSourceFile(
		path.pathname,
		readFileSync(path, 'utf8'),
		ts.ScriptTarget.Latest,
		true,
		ts.ScriptKind.TS,
	)
}

function requireInterface(sourceFile: ts.SourceFile, name: string): ts.InterfaceDeclaration {
	const found = sourceFile.statements.find(
		(statement): statement is ts.InterfaceDeclaration =>
			ts.isInterfaceDeclaration(statement) && statement.name.text === name,
	)
	if (!found) throw new Error(`@gramio/types does not export a ${name} interface`)
	return found
}

function assertCurrent(path: URL, generated: string, label: string): void {
	const current = readFileSync(path, 'utf8')
	if (current === generated) return
	const line = firstDifferentLine(current, generated)
	throw new Error(
		`Telegram ${label} inventory is stale at line ${line}. Run pnpm api:generate and review the diff.`,
	)
}

function propertyName(name: ts.PropertyName, sourceFile: ts.SourceFile): string {
	if (ts.isIdentifier(name) || ts.isStringLiteral(name) || ts.isNumericLiteral(name))
		return name.text
	return name.getText(sourceFile)
}

function firstDifferentLine(left: string, right: string): number {
	const leftLines = left.split('\n')
	const rightLines = right.split('\n')
	const count = Math.max(leftLines.length, rightLines.length)
	for (let index = 0; index < count; index++)
		if (leftLines[index] !== rightLines[index]) return index + 1
	return count
}
