import { transport } from './embedded-transport'
import { createSession } from './session'
import { documentStorage } from './storage'
// This module is generated by the native package store for one immutable active selection.
// @ts-expect-error Installed selection exists only in the release artifact.
import { plugins } from 'launcher:selection'

const session = createSession(
	transport,
	{
		configStorage: documentStorage(transport, 'config'),
		stateStorage: documentStorage(transport, 'state'),
	},
	plugins,
)
export const dispatch = session.dispatch
export const close = session.close
