import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { type ParseError, parse, printParseErrorCode } from 'jsonc-parser'
import { resolve } from 'pathe'

export const DEFAULT_HMR_CONFIG_BASENAME = 'pluxel.hmr.jsonc' as const

export type PluxelHmrConfigV1 = {
	version: 1
	profile: string
	defaults?: {
		roots?: 'auto' | string[]
		/**
		 * Extra entry globs (workspace-relative unless absolute).
		 *
		 * This is for non-package entry modules (e.g. demo modules like
		 * `packages/plugins/host/src/demo/PluginEventsDemo.ts`).
		 */
		include?: string[]
		exclude?: string[]
	}
	profiles: Record<
		string,
		{
			roots?: 'auto' | string[]
			enabled: string[]
			include?: string[]
			exclude?: string[]
		}
	>
}

export type PluxelHmrConfig = PluxelHmrConfigV1

export function createDefaultHmrConfigV1(): PluxelHmrConfigV1 {
	return {
		version: 1,
		profile: 'dev',
		defaults: {
			roots: 'auto',
			exclude: ['**/node_modules/**', '**/dist/**', '**/.turbo/**', '**/*.map'],
		},
		profiles: {
			dev: {
				enabled: [],
			},
		},
	}
}

export function defaultHmrConfigHeaderComment(): string {
	return [
		'// Generated by `pluxel hmr`.',
		'// Prefer using the interactive prompt to edit this file.',
		'// Manual edits are allowed but may be overwritten by the generator.',
		'',
	].join('\n')
}

export function resolveDefaultHmrConfigPath(rootDir: string) {
	return resolve(rootDir, DEFAULT_HMR_CONFIG_BASENAME)
}

export function parseHmrConfigV1Jsonc(contents: string, label = DEFAULT_HMR_CONFIG_BASENAME): PluxelHmrConfigV1 {
	const errors: ParseError[] = []
	const data = parse(contents, errors, {
		allowTrailingComma: true,
		disallowComments: false,
	})
	if (errors.length) {
		const summary = errors.map((e) => `${printParseErrorCode(e.error)} at offset ${e.offset}`).join(', ')
		throw new Error(`[hmr-config] Failed to parse ${label}: ${summary}`)
	}
	return validateHmrConfigV1Strict(data, label)
}

export function readHmrConfigV1(configPath: string): PluxelHmrConfigV1 {
	if (!existsSync(configPath)) throw new Error(`[hmr-config] Missing config file: ${configPath}`)
	const raw = readFileSync(configPath, 'utf8')
	return parseHmrConfigV1Jsonc(raw, configPath)
}

export function writeHmrConfigV1(
	configPath: string,
	config: PluxelHmrConfigV1,
	opts?: { headerComment?: string },
) {
	const header = opts?.headerComment ?? defaultHmrConfigHeaderComment()
	const normalized = normalizeHmrConfigV1(config)
	const json = JSON.stringify(normalized, null, '\t')
	const out = header ? `${header}${json}\n` : `${json}\n`
	writeFileSync(configPath, out, 'utf8')
}

export function ensureHmrConfigV1(configPath: string): PluxelHmrConfigV1 {
	if (existsSync(configPath)) return readHmrConfigV1(configPath)
	const cfg = createDefaultHmrConfigV1()
	writeHmrConfigV1(configPath, cfg)
	return cfg
}

export function backupAndRewriteHmrConfigV1(configPath: string, next: PluxelHmrConfigV1) {
	const ts = new Date().toISOString().replace(/[:.]/g, '-')
	const backupPath = `${configPath}.bak.${ts}`
	const raw = readFileSync(configPath, 'utf8')
	writeFileSync(backupPath, raw, 'utf8')
	writeHmrConfigV1(configPath, next)
	return { backupPath }
}

function assertPlainObject(value: unknown, ctx: string): asserts value is Record<string, unknown> {
	if (!value || typeof value !== 'object' || Array.isArray(value)) {
		throw new Error(`[hmr-config] ${ctx} must be an object`)
	}
}

function assertString(value: unknown, ctx: string): asserts value is string {
	if (typeof value !== 'string' || !value.trim()) throw new Error(`[hmr-config] ${ctx} must be a non-empty string`)
}

function assertStringArray(value: unknown, ctx: string): asserts value is string[] {
	if (!Array.isArray(value) || value.some((v) => typeof v !== 'string')) {
		throw new Error(`[hmr-config] ${ctx} must be string[]`)
	}
}

function assertRoots(value: unknown, ctx: string): asserts value is 'auto' | string[] {
	if (value === 'auto') return
	assertStringArray(value, ctx)
}

function assertNoUnknownKeys(obj: Record<string, unknown>, allowed: readonly string[], ctx: string) {
	const allow = new Set(allowed)
	const unknown = Object.keys(obj).filter((k) => !allow.has(k))
	if (unknown.length) throw new Error(`[hmr-config] Unknown field(s) in ${ctx}: ${unknown.join(', ')}`)
}

export function validateHmrConfigV1Strict(raw: unknown, label = DEFAULT_HMR_CONFIG_BASENAME): PluxelHmrConfigV1 {
	assertPlainObject(raw, label)
	assertNoUnknownKeys(raw, ['version', 'profile', 'defaults', 'profiles'], label)

	if ((raw as any).version !== 1) throw new Error(`[hmr-config] ${label}: version must be 1`)
	assertString((raw as any).profile, `${label}.profile`)

	const defaultsRaw = (raw as any).defaults
	if (defaultsRaw !== undefined) {
		assertPlainObject(defaultsRaw, `${label}.defaults`)
		assertNoUnknownKeys(defaultsRaw, ['roots', 'include', 'exclude'], `${label}.defaults`)
		if ((defaultsRaw as any).roots !== undefined) assertRoots((defaultsRaw as any).roots, `${label}.defaults.roots`)
		if ((defaultsRaw as any).include !== undefined)
			assertStringArray((defaultsRaw as any).include, `${label}.defaults.include`)
		if ((defaultsRaw as any).exclude !== undefined)
			assertStringArray((defaultsRaw as any).exclude, `${label}.defaults.exclude`)
	}

	const profilesRaw = (raw as any).profiles
	assertPlainObject(profilesRaw, `${label}.profiles`)
	for (const [name, profileRaw] of Object.entries(profilesRaw as Record<string, unknown>)) {
		assertPlainObject(profileRaw, `${label}.profiles.${name}`)
		assertNoUnknownKeys(profileRaw, ['roots', 'enabled', 'include', 'exclude'], `${label}.profiles.${name}`)
		if ((profileRaw as any).roots !== undefined)
			assertRoots((profileRaw as any).roots, `${label}.profiles.${name}.roots`)
		assertStringArray((profileRaw as any).enabled, `${label}.profiles.${name}.enabled`)
		if ((profileRaw as any).include !== undefined)
			assertStringArray((profileRaw as any).include, `${label}.profiles.${name}.include`)
		if ((profileRaw as any).exclude !== undefined)
			assertStringArray((profileRaw as any).exclude, `${label}.profiles.${name}.exclude`)
	}

	return raw as PluxelHmrConfigV1
}

function normalizeHmrConfigV1(config: PluxelHmrConfigV1): PluxelHmrConfigV1 {
	const defaults = config.defaults
		? {
				...(config.defaults.roots !== undefined ? { roots: config.defaults.roots } : {}),
				...(config.defaults.include?.length ? { include: [...config.defaults.include] } : {}),
				...(config.defaults.exclude?.length ? { exclude: [...config.defaults.exclude] } : {}),
			}
		: undefined

	const profiles: PluxelHmrConfigV1['profiles'] = {}
	for (const key of Object.keys(config.profiles)) {
		const p = config.profiles[key]!
		profiles[key] = {
			...(p.roots !== undefined ? { roots: p.roots } : {}),
			enabled: [...p.enabled],
			...(p.include?.length ? { include: [...p.include] } : {}),
			...(p.exclude?.length ? { exclude: [...p.exclude] } : {}),
		}
	}

	return {
		version: 1,
		profile: config.profile,
		...(defaults ? { defaults } : {}),
		profiles,
	}
}

