import { writeFileSync } from 'node:fs'
import type { DiscoveredPlugin } from '@pluxel/hmr/diagnose'
import { toRootRelative, uniqSorted } from '@pluxel/hmr/diagnose'
import { dirname, resolve } from 'pathe'

export const DEFAULT_HMR_DISCOVERED_BASENAME = 'pluxel.hmr.discovered.jsonc' as const

export function defaultHmrDiscoveredIndexHeaderComment(): string {
	return [
		'// Generated by `pluxel hmr`.',
		'// Reference-only: helps humans/LLMs edit pluxel.hmr.jsonc without running the CLI.',
		'// Do not edit this file manually; re-run `pluxel hmr doctor` (or `pluxel hmr`) to refresh.',
		'',
	].join('\n')
}

export function resolveHmrDiscoveredIndexPath(configPath: string) {
	return resolve(dirname(configPath), DEFAULT_HMR_DISCOVERED_BASENAME)
}

export function writeHmrDiscoveredIndex(params: {
	rootDir: string
	configPath: string
	activeProfile: string
	rootsExpandedAbs?: string[]
	excludeGlobs?: string[]
	hiddenPackages?: string[]
	builtinPackages?: string[]
	omitFromEntries?: string[]
	discovered: DiscoveredPlugin[]
}) {
	const rootDirAbs = resolve(params.rootDir)
	const discoveredSorted = params.discovered
		.slice()
		.sort((a, b) => a.name.localeCompare(b.name) || a.pkgDir.localeCompare(b.pkgDir))

	const builtinPackages = uniqSorted((params.builtinPackages ?? []).map(String).filter(Boolean))
	const omitFromEntries = uniqSorted((params.omitFromEntries ?? []).map(String).filter(Boolean))
	const hiddenPackages = uniqSorted((params.hiddenPackages ?? []).map(String).filter(Boolean))

	const discoveredNames = uniqSorted(discoveredSorted.map((p) => p.name))
	const enabledCandidates = discoveredNames.filter((n) => !builtinPackages.includes(n))

	const rootsExpanded = params.rootsExpandedAbs?.length
		? params.rootsExpandedAbs.map((abs) => toRootRelative(rootDirAbs, abs))
		: undefined

	const payload = {
		generatedAt: new Date().toISOString(),
		config: {
			path: toRootRelative(rootDirAbs, params.configPath),
			activeProfile: params.activeProfile,
		},
		workspace: {
			...(rootsExpanded ? { rootsExpanded } : {}),
			...(params.excludeGlobs?.length ? { excludeGlobs: params.excludeGlobs.slice() } : {}),
			...(hiddenPackages.length ? { hiddenPackages } : {}),
		},
		builtin: {
			...(builtinPackages.length ? { packages: builtinPackages } : {}),
			...(omitFromEntries.length ? { omitFromEntries } : {}),
		},
		discovered: {
			count: discoveredSorted.length,
			packageNames: discoveredNames,
			enabledCandidates,
			pluginPackages: discoveredSorted.map((p) => ({
				name: p.name,
				pkgDir: p.pkgDir,
				entry: p.entry,
			})),
		},
	}

	const outPath = resolveHmrDiscoveredIndexPath(params.configPath)
	const header = defaultHmrDiscoveredIndexHeaderComment()
	const json = JSON.stringify(payload, null, '\t')
	writeFileSync(outPath, `${header}${json}\n`, 'utf8')
}
