import { defineConfig } from 'tsdown'
export default defineConfig({
	exports: { devExports: '@pluxel/source' },
	copy: ['public'],
	entry: {
		test: 'src/test.ts',
		'internal/test': 'src/internal-test.ts',
		shell: 'src/shell.ts',
		http: 'src/http.ts',
		'internal/shell': 'src/shell/internal.ts',
		index: 'src/index.ts',
		service: 'src/service.ts',
		server: 'src/server.ts',
		internal: 'src/internal.ts',
		client: 'src/workbench/client.ts',
		react: 'src/workbench/react.tsx',
		federation: 'src/workbench/federation.ts',
		'internal/react': 'src/workbench/react-internal.tsx',
		'internal/definition': 'src/workbench/definition.ts',
		paths: 'src/paths.ts',
		dev: 'src/dev.ts',
	},
	deps: {
		neverBundle: [
			'@pluxel/core',
			'@pluxel/core/*',
			'@pluxel/host',
			'@pluxel/management',
			'@pluxel/management/*',
			'@pluxel/services/*',
			'@pluxel/host-dev',
			'@pluxel/host-dev/*',
			'@pluxel/rolldown',
			'@pluxel/rolldown/*',
			'vite',
			'vite/*',
			'capnweb',
			'react',
			'react-dom',
		],
	},
	dts: { eager: true },
	format: ['esm'],
	clean: true,
	sourcemap: true,
})
