import {
	DEFAULT_ZHIPU_CHAT_MODEL,
	DEFAULT_ZHIPU_LAYOUT_MODEL,
	DEFAULT_ZHIPU_TOKENIZER_MODEL,
} from '@repo/external-api-gateway-shared/constants'
import type { ProviderDescriptor } from '@repo/external-api-gateway-shared/provider'

export const zhipuProviderDescriptor: ProviderDescriptor = {
	id: 'zhipu',
	label: 'Zhipu OpenAPI',
	pluginId: 'ZhipuProviderPlugin',
	operations: [
		{
			id: 'ocr.layout_parsing',
			label: 'GLM OCR layout parsing',
			path: '/layout_parsing',
			method: 'POST',
			defaultModel: DEFAULT_ZHIPU_LAYOUT_MODEL,
			unitName: 'request',
			inputKind: 'json',
		},
		{
			id: 'ocr.files',
			label: 'Files OCR',
			path: '/files/ocr',
			method: 'POST',
			unitName: 'request',
			inputKind: 'multipart',
		},
		{
			id: 'file_parser.create',
			label: 'File parser async create',
			path: '/files/parser/create',
			method: 'POST',
			unitName: 'request',
			inputKind: 'multipart',
		},
		{
			id: 'file_parser.result',
			label: 'File parser async result',
			path: '/files/parser/result/{task_id}/{format_type}',
			method: 'GET',
			unitName: 'request',
			inputKind: 'path',
		},
		{
			id: 'file_parser.sync',
			label: 'File parser sync',
			path: '/files/parser/sync',
			method: 'POST',
			unitName: 'request',
			inputKind: 'multipart',
		},
		{
			id: 'chat.completions',
			label: 'Chat completions',
			path: '/chat/completions',
			method: 'POST',
			defaultModel: DEFAULT_ZHIPU_CHAT_MODEL,
			unitName: 'token',
			inputKind: 'json',
		},
		{
			id: 'tokenizer',
			label: 'Text tokenizer',
			path: '/tokenizer',
			method: 'POST',
			defaultModel: DEFAULT_ZHIPU_TOKENIZER_MODEL,
			unitName: 'token',
			inputKind: 'json',
		},
		{
			id: 'embeddings.create',
			label: 'Embeddings',
			path: '/embeddings',
			method: 'POST',
			unitName: 'token',
			inputKind: 'json',
		},
		{
			id: 'rerank.create',
			label: 'Rerank',
			path: '/rerank',
			method: 'POST',
			unitName: 'request',
			inputKind: 'json',
		},
		{
			id: 'reader',
			label: 'Reader',
			path: '/reader',
			method: 'POST',
			unitName: 'request',
			inputKind: 'json',
		},
		{
			id: 'moderations.create',
			label: 'Moderations',
			path: '/moderations',
			method: 'POST',
			unitName: 'request',
			inputKind: 'json',
		},
		{
			id: 'web_search',
			label: 'Web search',
			path: '/web_search',
			method: 'POST',
			unitName: 'request',
			inputKind: 'json',
		},
	],
}
