import { defineConfig } from 'pncat'

export default defineConfig({
	catalogRules: [
		{
			name: 'pluxel',
			match: [/^@pluxel\//],
			priority: 10,
		},
		{
			name: 'frontend',
			match: [
				/^@dnd-kit\//,
				/^@heroui\//,
				/^@mantine\//,
				/^@tabler\//,
				/^@tailwindcss\//,
				/^@tanstack\//,
				/^@types\/react(?:-dom)?$/,
				/^@vibrant\//,
				'@vitejs/plugin-react',
				'lucide-react',
				'react',
				'react-dom',
				'tailwindcss',
			],
			priority: 20,
		},
		{
			name: 'test',
			match: [/^@testing-library\//, 'playwright', 'vitest'],
			priority: 30,
		},
		{
			name: 'backend',
			match: [
				/^@discordjs\//,
				/^@gqloom\//,
				'@libsql/client',
				'capnweb',
				'cbor-x',
				'discord.js',
				'drizzle-orm',
				'elysia',
				'fractional-indexing',
				'graphql',
				'graphql-yoga',
				'nanoid',
				'qrcode',
				'valibot',
				'wretch',
			],
			priority: 40,
		},
		{
			name: 'tooling',
			match: [
				/^@types\//,
				'@napi-rs/cli',
				'electron',
				'electron-builder',
				'oxfmt',
				'oxlint',
				'pncat',
				'portless',
				'sass-embedded',
				'tsdown',
				'turbo',
				'typescript',
				'vite',
			],
			priority: 50,
		},
	],
})
