import { type ParseError, parse, printParseErrorCode } from 'jsonc-parser'
import { resolve } from 'pathe'
import { nodeLoaderHmrWorkspaceFs, type LoaderHmrWorkspaceFs } from './fs'

export const DEFAULT_LOADER_HMR_CONFIG_BASENAME = 'pluxel.loader.hmr.jsonc' as const

export type PluxelLoaderHmrConfigV2 = {
	version: 2
	profile: string
	defaults?: {
		roots?: 'auto' | string[]
		/**
		 * Extra entry globs (workspace-relative unless absolute).
		 *
		 * This is for non-package entry modules (e.g. demo modules like
		 * `projects/plugin-host/src/demo/PluginEventsDemo.ts`).
		 */
		include?: string[]
		exclude?: string[]
	}
	profiles: Record<
		string,
		{
			roots?: 'auto' | string[]
			enabled: string[]
			include?: string[]
			exclude?: string[]
		}
	>
}

export type PluxelLoaderHmrConfig = PluxelLoaderHmrConfigV2

export function createDefaultLoaderHmrConfigV2(): PluxelLoaderHmrConfigV2 {
	return {
		version: 2,
		profile: 'hmr',
		defaults: {
			roots: 'auto',
			exclude: ['**/node_modules/**', '**/dist/**', '**/.turbo/**', '**/*.map'],
		},
		profiles: {
			hmr: {
				enabled: [],
			},
		},
	}
}

export function defaultLoaderHmrConfigHeaderComment(): string {
	return [
		'// Generated by `pluxel hmr`.',
		'// Prefer using the interactive prompt to edit this file.',
		'// Tip: `pluxel.loader.hmr.discovered.jsonc` is generated to list available plugin packages for profiles.',
		'// Manual edits are allowed but may be overwritten by the generator.',
		'',
	].join('\n')
}

export function resolveDefaultLoaderHmrConfigPath(rootDir: string) {
	return resolve(rootDir, DEFAULT_LOADER_HMR_CONFIG_BASENAME)
}

export function parseLoaderHmrConfigV2Jsonc(
	contents: string,
	label: string = DEFAULT_LOADER_HMR_CONFIG_BASENAME,
): PluxelLoaderHmrConfigV2 {
	const errors: ParseError[] = []
	const data = parse(contents, errors, {
		allowTrailingComma: true,
		disallowComments: false,
	})
	if (errors.length > 0) {
		const summary = errors
			.map((e) => `${printParseErrorCode(e.error)} at offset ${e.offset}`)
			.join(', ')
		throw new Error(`[loader-hmr-config] Failed to parse ${label}: ${summary}`)
	}
	return validateLoaderHmrConfigV2Strict(data, label)
}

export function readLoaderHmrConfigV2(
	configPath: string,
	fs: LoaderHmrWorkspaceFs = nodeLoaderHmrWorkspaceFs,
): PluxelLoaderHmrConfigV2 {
	if (!fs.existsSync(configPath))
		throw new Error(`[loader-hmr-config] Missing config file: ${configPath}`)
	const raw = readLoaderHmrConfigText(configPath, fs)
	return parseLoaderHmrConfigV2Jsonc(raw, configPath)
}

export function writeLoaderHmrConfigV2(
	configPath: string,
	config: PluxelLoaderHmrConfigV2,
	opts?: { headerComment?: string; fs?: LoaderHmrWorkspaceFs },
) {
	const header = opts?.headerComment ?? defaultLoaderHmrConfigHeaderComment()
	const normalized = normalizeLoaderHmrConfigV2(config)
	const json = JSON.stringify(normalized, null, '\t')
	const out = header ? `${header}${json}\n` : `${json}\n`
	;(opts?.fs ?? nodeLoaderHmrWorkspaceFs).writeFileSync(configPath, out, 'utf8')
}

export function ensureLoaderHmrConfigV2(
	configPath: string,
	fs: LoaderHmrWorkspaceFs = nodeLoaderHmrWorkspaceFs,
): PluxelLoaderHmrConfigV2 {
	if (fs.existsSync(configPath)) return readLoaderHmrConfigV2(configPath, fs)
	const cfg = createDefaultLoaderHmrConfigV2()
	writeLoaderHmrConfigV2(configPath, cfg, { fs })
	return cfg
}

export function backupAndRewriteLoaderHmrConfigV2(
	configPath: string,
	next: PluxelLoaderHmrConfigV2,
	fs: LoaderHmrWorkspaceFs = nodeLoaderHmrWorkspaceFs,
) {
	const ts = new Date().toISOString().replaceAll(/[:.]/g, '-')
	const backupPath = `${configPath}.bak.${ts}`
	const raw = readLoaderHmrConfigText(configPath, fs)
	fs.writeFileSync(backupPath, raw, 'utf8')
	writeLoaderHmrConfigV2(configPath, next, { fs })
	return { backupPath }
}

function readLoaderHmrConfigText(configPath: string, fs: LoaderHmrWorkspaceFs): string {
	return fs.readFileSync(configPath, 'utf8').toString()
}

function assertPlainObject(value: unknown, ctx: string): asserts value is Record<string, unknown> {
	if (!value || typeof value !== 'object' || Array.isArray(value)) {
		throw new Error(`[loader-hmr-config] ${ctx} must be an object`)
	}
}

function assertString(value: unknown, ctx: string): asserts value is string {
	if (typeof value !== 'string' || !value.trim())
		throw new Error(`[loader-hmr-config] ${ctx} must be a non-empty string`)
}

function assertStringArray(value: unknown, ctx: string): asserts value is string[] {
	if (!Array.isArray(value) || value.some((v) => typeof v !== 'string')) {
		throw new Error(`[loader-hmr-config] ${ctx} must be string[]`)
	}
}

function assertRoots(value: unknown, ctx: string): asserts value is 'auto' | string[] {
	if (value === 'auto') return
	assertStringArray(value, ctx)
}

function assertNoUnknownKeys(
	obj: Record<string, unknown>,
	allowed: readonly string[],
	ctx: string,
) {
	const allow = new Set(allowed)
	const unknown = Object.keys(obj).filter((k) => !allow.has(k))
	if (unknown.length > 0)
		throw new Error(`[loader-hmr-config] Unknown field(s) in ${ctx}: ${unknown.join(', ')}`)
}

export function validateLoaderHmrConfigV2Strict(
	raw: unknown,
	label: string = DEFAULT_LOADER_HMR_CONFIG_BASENAME,
): PluxelLoaderHmrConfigV2 {
	assertPlainObject(raw, label)
	assertNoUnknownKeys(raw, ['version', 'profile', 'defaults', 'profiles'], label)

	if (raw.version === 1) {
		throw new Error(
			`[loader-hmr-config] ${label}: version 1 is unsupported; remove profile builtin fields and set version to 2`,
		)
	}
	if (raw.version !== 2) throw new Error(`[loader-hmr-config] ${label}: version must be 2`)
	assertString(raw.profile, `${label}.profile`)

	const defaultsRaw = raw.defaults
	if (defaultsRaw !== undefined) {
		assertPlainObject(defaultsRaw, `${label}.defaults`)
		assertNoUnknownKeys(defaultsRaw, ['roots', 'include', 'exclude'], `${label}.defaults`)
		if (defaultsRaw.roots !== undefined) assertRoots(defaultsRaw.roots, `${label}.defaults.roots`)
		if (defaultsRaw.include !== undefined)
			assertStringArray(defaultsRaw.include, `${label}.defaults.include`)
		if (defaultsRaw.exclude !== undefined)
			assertStringArray(defaultsRaw.exclude, `${label}.defaults.exclude`)
	}

	const profilesRaw = raw.profiles
	assertPlainObject(profilesRaw, `${label}.profiles`)
	for (const [name, profileRaw] of Object.entries(profilesRaw as Record<string, unknown>)) {
		assertPlainObject(profileRaw, `${label}.profiles.${name}`)
		assertNoUnknownKeys(
			profileRaw,
			['roots', 'enabled', 'include', 'exclude'],
			`${label}.profiles.${name}`,
		)
		if (profileRaw.roots !== undefined)
			assertRoots(profileRaw.roots, `${label}.profiles.${name}.roots`)
		assertStringArray(profileRaw.enabled, `${label}.profiles.${name}.enabled`)
		if (profileRaw.include !== undefined)
			assertStringArray(profileRaw.include, `${label}.profiles.${name}.include`)
		if (profileRaw.exclude !== undefined)
			assertStringArray(profileRaw.exclude, `${label}.profiles.${name}.exclude`)
	}

	return raw as PluxelLoaderHmrConfigV2
}

function normalizeLoaderHmrConfigV2(config: PluxelLoaderHmrConfigV2): PluxelLoaderHmrConfigV2 {
	const defaults = config.defaults
		? {
				...(config.defaults.roots !== undefined ? { roots: config.defaults.roots } : {}),
				...(config.defaults.include?.length ? { include: [...config.defaults.include] } : {}),
				...(config.defaults.exclude?.length ? { exclude: [...config.defaults.exclude] } : {}),
			}
		: undefined

	const profiles: PluxelLoaderHmrConfigV2['profiles'] = {}
	for (const key of Object.keys(config.profiles)) {
		const p = config.profiles[key]!
		profiles[key] = {
			...(p.roots !== undefined ? { roots: p.roots } : {}),
			enabled: [...p.enabled],
			...(p.include?.length ? { include: [...p.include] } : {}),
			...(p.exclude?.length ? { exclude: [...p.exclude] } : {}),
		}
	}

	return {
		version: 2,
		profile: config.profile,
		...(defaults ? { defaults } : {}),
		profiles,
	}
}
