/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkbenchRouteImport } from './routes/_workbench'
import { Route as StandaloneRouteImport } from './routes/_standalone'
import { Route as WorkbenchIndexRouteImport } from './routes/_workbench.index'
import { Route as WorkbenchPluginsRouteImport } from './routes/_workbench.plugins'
import { Route as WorkbenchPackagesRouteImport } from './routes/_workbench.packages'
import { Route as WorkbenchLogsRouteImport } from './routes/_workbench.logs'
import { Route as WorkbenchPluginsIndexRouteImport } from './routes/_workbench.plugins.index'
import { Route as WorkbenchPluginsNameRouteImport } from './routes/_workbench.plugins.$name'
import { Route as WorkbenchPluginsNameIndexRouteImport } from './routes/_workbench.plugins.$name.index'
import { Route as WorkbenchPluginsNameSplatRouteImport } from './routes/_workbench.plugins.$name.$'
import { Route as WorkbenchExtPluginNameSplatRouteImport } from './routes/_workbench.ext.$pluginName.$'
import { Route as StandaloneExtStandalonePluginNameSplatRouteImport } from './routes/_standalone.ext-standalone.$pluginName.$'

const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/_workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const StandaloneRoute = StandaloneRouteImport.update({
  id: '/_standalone',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchIndexRoute = WorkbenchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkbenchRoute,
} as any)
const WorkbenchPluginsRoute = WorkbenchPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => WorkbenchRoute,
} as any)
const WorkbenchPackagesRoute = WorkbenchPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => WorkbenchRoute,
} as any)
const WorkbenchLogsRoute = WorkbenchLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => WorkbenchRoute,
} as any)
const WorkbenchPluginsIndexRoute = WorkbenchPluginsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkbenchPluginsRoute,
} as any)
const WorkbenchPluginsNameRoute = WorkbenchPluginsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => WorkbenchPluginsRoute,
} as any)
const WorkbenchPluginsNameIndexRoute =
  WorkbenchPluginsNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkbenchPluginsNameRoute,
  } as any)
const WorkbenchPluginsNameSplatRoute =
  WorkbenchPluginsNameSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => WorkbenchPluginsNameRoute,
  } as any)
const WorkbenchExtPluginNameSplatRoute =
  WorkbenchExtPluginNameSplatRouteImport.update({
    id: '/ext/$pluginName/$',
    path: '/ext/$pluginName/$',
    getParentRoute: () => WorkbenchRoute,
  } as any)
const StandaloneExtStandalonePluginNameSplatRoute =
  StandaloneExtStandalonePluginNameSplatRouteImport.update({
    id: '/ext-standalone/$pluginName/$',
    path: '/ext-standalone/$pluginName/$',
    getParentRoute: () => StandaloneRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkbenchIndexRoute
  '/logs': typeof WorkbenchLogsRoute
  '/packages': typeof WorkbenchPackagesRoute
  '/plugins': typeof WorkbenchPluginsRouteWithChildren
  '/plugins/$name': typeof WorkbenchPluginsNameRouteWithChildren
  '/plugins/': typeof WorkbenchPluginsIndexRoute
  '/ext-standalone/$pluginName/$': typeof StandaloneExtStandalonePluginNameSplatRoute
  '/ext/$pluginName/$': typeof WorkbenchExtPluginNameSplatRoute
  '/plugins/$name/$': typeof WorkbenchPluginsNameSplatRoute
  '/plugins/$name/': typeof WorkbenchPluginsNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof WorkbenchIndexRoute
  '/logs': typeof WorkbenchLogsRoute
  '/packages': typeof WorkbenchPackagesRoute
  '/plugins': typeof WorkbenchPluginsIndexRoute
  '/ext-standalone/$pluginName/$': typeof StandaloneExtStandalonePluginNameSplatRoute
  '/ext/$pluginName/$': typeof WorkbenchExtPluginNameSplatRoute
  '/plugins/$name/$': typeof WorkbenchPluginsNameSplatRoute
  '/plugins/$name': typeof WorkbenchPluginsNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_standalone': typeof StandaloneRouteWithChildren
  '/_workbench': typeof WorkbenchRouteWithChildren
  '/_workbench/logs': typeof WorkbenchLogsRoute
  '/_workbench/packages': typeof WorkbenchPackagesRoute
  '/_workbench/plugins': typeof WorkbenchPluginsRouteWithChildren
  '/_workbench/': typeof WorkbenchIndexRoute
  '/_workbench/plugins/$name': typeof WorkbenchPluginsNameRouteWithChildren
  '/_workbench/plugins/': typeof WorkbenchPluginsIndexRoute
  '/_standalone/ext-standalone/$pluginName/$': typeof StandaloneExtStandalonePluginNameSplatRoute
  '/_workbench/ext/$pluginName/$': typeof WorkbenchExtPluginNameSplatRoute
  '/_workbench/plugins/$name/$': typeof WorkbenchPluginsNameSplatRoute
  '/_workbench/plugins/$name/': typeof WorkbenchPluginsNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logs'
    | '/packages'
    | '/plugins'
    | '/plugins/$name'
    | '/plugins/'
    | '/ext-standalone/$pluginName/$'
    | '/ext/$pluginName/$'
    | '/plugins/$name/$'
    | '/plugins/$name/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logs'
    | '/packages'
    | '/plugins'
    | '/ext-standalone/$pluginName/$'
    | '/ext/$pluginName/$'
    | '/plugins/$name/$'
    | '/plugins/$name'
  id:
    | '__root__'
    | '/_standalone'
    | '/_workbench'
    | '/_workbench/logs'
    | '/_workbench/packages'
    | '/_workbench/plugins'
    | '/_workbench/'
    | '/_workbench/plugins/$name'
    | '/_workbench/plugins/'
    | '/_standalone/ext-standalone/$pluginName/$'
    | '/_workbench/ext/$pluginName/$'
    | '/_workbench/plugins/$name/$'
    | '/_workbench/plugins/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StandaloneRoute: typeof StandaloneRouteWithChildren
  WorkbenchRoute: typeof WorkbenchRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workbench': {
      id: '/_workbench'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_standalone': {
      id: '/_standalone'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StandaloneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workbench/': {
      id: '/_workbench/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkbenchIndexRouteImport
      parentRoute: typeof WorkbenchRoute
    }
    '/_workbench/plugins': {
      id: '/_workbench/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof WorkbenchPluginsRouteImport
      parentRoute: typeof WorkbenchRoute
    }
    '/_workbench/packages': {
      id: '/_workbench/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof WorkbenchPackagesRouteImport
      parentRoute: typeof WorkbenchRoute
    }
    '/_workbench/logs': {
      id: '/_workbench/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof WorkbenchLogsRouteImport
      parentRoute: typeof WorkbenchRoute
    }
    '/_workbench/plugins/': {
      id: '/_workbench/plugins/'
      path: '/'
      fullPath: '/plugins/'
      preLoaderRoute: typeof WorkbenchPluginsIndexRouteImport
      parentRoute: typeof WorkbenchPluginsRoute
    }
    '/_workbench/plugins/$name': {
      id: '/_workbench/plugins/$name'
      path: '/$name'
      fullPath: '/plugins/$name'
      preLoaderRoute: typeof WorkbenchPluginsNameRouteImport
      parentRoute: typeof WorkbenchPluginsRoute
    }
    '/_workbench/plugins/$name/': {
      id: '/_workbench/plugins/$name/'
      path: '/'
      fullPath: '/plugins/$name/'
      preLoaderRoute: typeof WorkbenchPluginsNameIndexRouteImport
      parentRoute: typeof WorkbenchPluginsNameRoute
    }
    '/_workbench/plugins/$name/$': {
      id: '/_workbench/plugins/$name/$'
      path: '/$'
      fullPath: '/plugins/$name/$'
      preLoaderRoute: typeof WorkbenchPluginsNameSplatRouteImport
      parentRoute: typeof WorkbenchPluginsNameRoute
    }
    '/_workbench/ext/$pluginName/$': {
      id: '/_workbench/ext/$pluginName/$'
      path: '/ext/$pluginName/$'
      fullPath: '/ext/$pluginName/$'
      preLoaderRoute: typeof WorkbenchExtPluginNameSplatRouteImport
      parentRoute: typeof WorkbenchRoute
    }
    '/_standalone/ext-standalone/$pluginName/$': {
      id: '/_standalone/ext-standalone/$pluginName/$'
      path: '/ext-standalone/$pluginName/$'
      fullPath: '/ext-standalone/$pluginName/$'
      preLoaderRoute: typeof StandaloneExtStandalonePluginNameSplatRouteImport
      parentRoute: typeof StandaloneRoute
    }
  }
}

interface StandaloneRouteChildren {
  StandaloneExtStandalonePluginNameSplatRoute: typeof StandaloneExtStandalonePluginNameSplatRoute
}

const StandaloneRouteChildren: StandaloneRouteChildren = {
  StandaloneExtStandalonePluginNameSplatRoute:
    StandaloneExtStandalonePluginNameSplatRoute,
}

const StandaloneRouteWithChildren = StandaloneRoute._addFileChildren(
  StandaloneRouteChildren,
)

interface WorkbenchPluginsNameRouteChildren {
  WorkbenchPluginsNameSplatRoute: typeof WorkbenchPluginsNameSplatRoute
  WorkbenchPluginsNameIndexRoute: typeof WorkbenchPluginsNameIndexRoute
}

const WorkbenchPluginsNameRouteChildren: WorkbenchPluginsNameRouteChildren = {
  WorkbenchPluginsNameSplatRoute: WorkbenchPluginsNameSplatRoute,
  WorkbenchPluginsNameIndexRoute: WorkbenchPluginsNameIndexRoute,
}

const WorkbenchPluginsNameRouteWithChildren =
  WorkbenchPluginsNameRoute._addFileChildren(WorkbenchPluginsNameRouteChildren)

interface WorkbenchPluginsRouteChildren {
  WorkbenchPluginsNameRoute: typeof WorkbenchPluginsNameRouteWithChildren
  WorkbenchPluginsIndexRoute: typeof WorkbenchPluginsIndexRoute
}

const WorkbenchPluginsRouteChildren: WorkbenchPluginsRouteChildren = {
  WorkbenchPluginsNameRoute: WorkbenchPluginsNameRouteWithChildren,
  WorkbenchPluginsIndexRoute: WorkbenchPluginsIndexRoute,
}

const WorkbenchPluginsRouteWithChildren =
  WorkbenchPluginsRoute._addFileChildren(WorkbenchPluginsRouteChildren)

interface WorkbenchRouteChildren {
  WorkbenchLogsRoute: typeof WorkbenchLogsRoute
  WorkbenchPackagesRoute: typeof WorkbenchPackagesRoute
  WorkbenchPluginsRoute: typeof WorkbenchPluginsRouteWithChildren
  WorkbenchIndexRoute: typeof WorkbenchIndexRoute
  WorkbenchExtPluginNameSplatRoute: typeof WorkbenchExtPluginNameSplatRoute
}

const WorkbenchRouteChildren: WorkbenchRouteChildren = {
  WorkbenchLogsRoute: WorkbenchLogsRoute,
  WorkbenchPackagesRoute: WorkbenchPackagesRoute,
  WorkbenchPluginsRoute: WorkbenchPluginsRouteWithChildren,
  WorkbenchIndexRoute: WorkbenchIndexRoute,
  WorkbenchExtPluginNameSplatRoute: WorkbenchExtPluginNameSplatRoute,
}

const WorkbenchRouteWithChildren = WorkbenchRoute._addFileChildren(
  WorkbenchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  StandaloneRoute: StandaloneRouteWithChildren,
  WorkbenchRoute: WorkbenchRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
