import { mkdir, writeFile } from 'node:fs/promises'
import { resolve } from 'pathe'

import type {
	BuildFrozenHostOptions,
	BuildFrozenHostResult,
	FrozenPluginSpec,
} from './runtime/contracts'

type ImportRow = FrozenPluginSpec & { alias: string }

function safeIdent(input: string): string {
	let id = input.replaceAll(/[^A-Za-z0-9_$]/g, '_')
	if (!id) id = 'Plugin'
	if (/^[0-9]/.test(id)) id = `_${id}`
	return id
}

function buildImportRows(plugins: readonly FrozenPluginSpec[]): ImportRow[] {
	const used = new Set<string>()
	return plugins.map((plugin, index) => {
		let alias = safeIdent(
			`${plugin.packageName ?? plugin.moduleId ?? 'Plugin'}_${plugin.exportKey}_${index + 1}`,
		)
		while (used.has(alias)) alias = `${alias}_${used.size + 1}`
		used.add(alias)
		return { ...plugin, alias }
	})
}

function buildBootstrapSource(options: BuildFrozenHostOptions, rows: readonly ImportRow[]): string {
	const generatedBy = options.generatedBy ?? 'buildFrozenHost'
	const configPayload = options.config ?? {}
	const enabled = new Set(options.enabled)
	const profile = options.profile ?? 'frozen'
	const imports = rows
		.map((row) =>
			row.exportKey === 'default'
				? `import ${row.alias} from ${JSON.stringify(row.importPath)}`
				: `import { ${row.exportKey} as ${row.alias} } from ${JSON.stringify(row.importPath)}`,
		)
		.join('\n')

	const builtins = rows
		.map((row) => {
			const isEnabled = row.enable ?? enabled.has(row.moduleId)
			return `{ plugin: ${row.alias}, moduleId: ${JSON.stringify(row.moduleId)}, exportKey: ${JSON.stringify(
				row.exportKey,
			)}, enable: ${isEnabled ? 'true' : 'false'} }`
		})
		.join(',\n\t\t')

	return `// @generated by ${generatedBy}
/* eslint-disable */
import { Context } from '@pluxel/core'
import '@pluxel/core/services'
import '@pluxel/runtime'
import '@pluxel/runtime/services/vault'
import '@pluxel/runtime-dynamic/register'
${imports}

const ctx = new Context({
\tprofile: ${JSON.stringify(profile)},
\tconfigService: {
\t\t// Frozen hosts still need a mutable bootstrap phase because builtin preload
\t\t// records schema metadata into ConfigService. Keep it in-memory so the
\t\t// export stays side-effect free while allowing runtime baseline registration.
\t\tmode: 'memory',
\t\tsnapshot: {
\t\t\tplugins: ${JSON.stringify(configPayload, null, 2)},
\t\t},
\t},
\truntimeState: {
\t\tmode: 'memory',
\t\tsnapshot: {
\t\t\tenabled: ${JSON.stringify([...enabled])},
\t\t},
\t},
\tpackageService: {
\t\tpolicy: { allowInstall: false, allowUninstall: false },
\t\tstate: { enabled: false },
\t},
\thttp: ${JSON.stringify(options.bootstrap?.http ?? {})},
\tmanagement: ${JSON.stringify(options.bootstrap?.management ?? { enabled: false, access: { exposure: 'private' } })},
\textensionService: { enabled: false },
})

await ctx.prepareServices()

await ctx.loader.preloadPlugins(
\t[
\t\t${builtins}
\t],
\t{ strict: true, commit: true },
)

export default ctx
`
}

export async function buildFrozenHost(
	options: BuildFrozenHostOptions,
): Promise<BuildFrozenHostResult> {
	const dir = resolve(options.outDir)
	const entry = resolve(dir, 'frozen-host.mjs')
	const manifestPath = resolve(dir, 'frozen-manifest.json')
	const rows = buildImportRows(options.plugins)
	const source = buildBootstrapSource(options, rows)
	const fileOps = options.fs ?? { mkdir, writeFile }

	await fileOps.mkdir(dir, { recursive: true })
	await fileOps.writeFile(entry, source, 'utf-8')
	await fileOps.writeFile(
		manifestPath,
		JSON.stringify(
			{
				profile: options.profile ?? 'frozen',
				plugins: options.plugins,
				enabled: options.enabled ?? [],
			},
			null,
			2,
		),
		'utf-8',
	)

	return { dir, entry, manifestPath }
}
