export { workbenchContract } from './workbench/contracts'
export type {
	AnyWorkbenchContract,
	WorkbenchContract,
	WorkbenchEventsOf,
	WorkbenchEventsResource,
	StandardSchema,
	WorkbenchLiveQueryOf,
	WorkbenchLiveQueryResource,
	WorkbenchIcon,
	WorkbenchPlacementSpec,
	WorkbenchRoutePlacementSpec,
	WorkbenchPortContract,
	WorkbenchResourceContract,
	WorkbenchResourceMap,
	WorkbenchRpcOf,
	WorkbenchRpcResource,
	WorkbenchTabPlacementSpec,
	WorkbenchTabMeta,
	WorkbenchRouteMeta,
	WorkbenchViewSpec,
} from './workbench/contracts'
