export { workbench } from './workbench/definition'
export type {
	AnyWorkbenchDefinition,
	PluginWorkbench,
	WorkbenchAttachment,
	WorkbenchAttachmentOpenContext,
	WorkbenchAttachmentPlacement,
	WorkbenchAttachmentTargetFactory,
	WorkbenchBindings,
	WorkbenchDefinition,
	WorkbenchEntry,
	WorkbenchEntryMap,
	WorkbenchGroup,
	WorkbenchIcon,
	WorkbenchNavigation,
	WorkbenchPlacement,
	WorkbenchPrincipal,
	WorkbenchRendererEntry,
	WorkbenchRoutePlacement,
	WorkbenchTabPlacement,
	WorkbenchTargetFactory,
	WorkbenchView,
	WorkbenchViewOpenContext,
} from './workbench/definition'
