// Auto-generated by @gqlens/codegen
// Sections: typed nodes, schema contract, runtime entrypoints, selectors, mutation API.
import { useGQLensSession, useLiveGQLensSession, type QueryConfig as GQLensQueryConfig } from "@gqlens/react";
import {
  bindSelection as bindGQLensSelection,
  createAccessorNode,
  defineInvalidation as defineGQLensInvalidation,
  defineSelection as defineGQLensSelection,
  type AccessorContext,
  type GQLensSchemaContract,
} from "@gqlens/core/codegen";
import type {
  GraphDataInvalidation,
  MutationOperation,
  PreparedSelection,
  VariablePlaceholder,
} from "@gqlens/core";
import type * as Types from "./types";

type GQLensArgValue<T> =
  T extends readonly (infer Item)[]
    ? readonly GQLensArgValue<Item>[] | VariablePlaceholder
    : T extends object
      ? { readonly [Key in keyof T]: GQLensArgValue<T[Key]> } | VariablePlaceholder
      : T | VariablePlaceholder;
type GQLensArgs<T> = { readonly [Key in keyof T]: GQLensArgValue<T[Key]> };
type GQLensQueryOptions = Omit<GQLensQueryConfig, "schema">;

// Typed accessor nodes
export interface QueryNode {
  readonly __typename: string | undefined;
  readonly summary: SummaryNode;
  readonly customers: { readonly ids: readonly string[] | undefined };
  readonly customer: (args: GQLensArgs<Types.QueryCustomerArgs>) => CustomerNode;
  readonly orders: { readonly ids: readonly string[] | undefined };
  readonly order: (args: GQLensArgs<Types.QueryOrderArgs>) => OrderNode;
  readonly ordersByStatus: (args: GQLensArgs<Types.QueryOrdersByStatusArgs>) => { readonly ids: readonly string[] | undefined };
}

export interface SummaryNode {
  readonly __typename: string | undefined;
  readonly revenue: Types.Summary["revenue"] | undefined;
  readonly margin: Types.Summary["margin"] | undefined;
  readonly openOrders: Types.Summary["openOrders"] | undefined;
  readonly approvedOrders: Types.Summary["approvedOrders"] | undefined;
}

export interface CustomerNode {
  readonly __typename: string | undefined;
  readonly id: Types.Customer["id"] | undefined;
  readonly name: Types.Customer["name"] | undefined;
  readonly owner: Types.Customer["owner"] | undefined;
  readonly tier: Types.Customer["tier"] | undefined;
  readonly region: Types.Customer["region"] | undefined;
  readonly healthScore: Types.Customer["healthScore"] | undefined;
}

export interface OrderNode {
  readonly __typename: string | undefined;
  readonly id: Types.Order["id"] | undefined;
  readonly customerId: Types.Order["customerId"] | undefined;
  readonly sku: Types.Order["sku"] | undefined;
  readonly status: Types.Order["status"] | undefined;
  readonly amount: Types.Order["amount"] | undefined;
  readonly margin: Types.Order["margin"] | undefined;
}

// Schema contract consumed by @gqlens/core
export const gqlensSchema: GQLensSchemaContract = {
  query: {
    type: "Query",
    kind: "root",
    fields: {
      "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
      "summary": { name: "summary", result: { "kind": "object", "cardinality": "one", "typeName": "Summary", "objectKind": "value" } },
      "customers": { name: "customers", result: { "kind": "object", "cardinality": "list", "typeName": "Customer", "objectKind": "entity" } },
      "customer": { name: "customer", result: { "kind": "object", "cardinality": "one", "typeName": "Customer", "objectKind": "entity" }, args: { "id": "String!" } },
      "orders": { name: "orders", result: { "kind": "object", "cardinality": "list", "typeName": "Order", "objectKind": "entity" } },
      "order": { name: "order", result: { "kind": "object", "cardinality": "one", "typeName": "Order", "objectKind": "entity" }, args: { "id": "String!" } },
      "ordersByStatus": { name: "ordersByStatus", result: { "kind": "object", "cardinality": "list", "typeName": "Order", "objectKind": "entity" }, args: { "status": "OrdersByStatusStatusInput!" } },
    },
  },
  mutation: {
    type: "Mutation",
    kind: "root",
    fields: {
      "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
      "approveOrder": { name: "approveOrder", result: { "kind": "object", "cardinality": "one", "typeName": "Order", "objectKind": "entity" }, args: { "id": "String!" } },
      "updateOrderAmount": { name: "updateOrderAmount", result: { "kind": "object", "cardinality": "one", "typeName": "Order", "objectKind": "entity" }, args: { "id": "String!", "amount": "Float!" } },
      "setCustomerHealth": { name: "setCustomerHealth", result: { "kind": "object", "cardinality": "one", "typeName": "Customer", "objectKind": "entity" }, args: { "id": "String!", "score": "Float!" } },
    },
  },
  objects: {
    "Summary": {
      type: "Summary",
      kind: "value",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "revenue": { name: "revenue", result: { "kind": "scalar", "cardinality": "one" } },
        "margin": { name: "margin", result: { "kind": "scalar", "cardinality": "one" } },
        "openOrders": { name: "openOrders", result: { "kind": "scalar", "cardinality": "one" } },
        "approvedOrders": { name: "approvedOrders", result: { "kind": "scalar", "cardinality": "one" } },
      },
    },
    "Customer": {
      type: "Customer",
      kind: "entity",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "id": { name: "id", result: { "kind": "scalar", "cardinality": "one" } },
        "name": { name: "name", result: { "kind": "scalar", "cardinality": "one" } },
        "owner": { name: "owner", result: { "kind": "scalar", "cardinality": "one" } },
        "tier": { name: "tier", result: { "kind": "scalar", "cardinality": "one" } },
        "region": { name: "region", result: { "kind": "scalar", "cardinality": "one" } },
        "healthScore": { name: "healthScore", result: { "kind": "scalar", "cardinality": "one" } },
      },
    },
    "Order": {
      type: "Order",
      kind: "entity",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "id": { name: "id", result: { "kind": "scalar", "cardinality": "one" } },
        "customerId": { name: "customerId", result: { "kind": "scalar", "cardinality": "one" } },
        "sku": { name: "sku", result: { "kind": "scalar", "cardinality": "one" } },
        "status": { name: "status", result: { "kind": "scalar", "cardinality": "one" } },
        "amount": { name: "amount", result: { "kind": "scalar", "cardinality": "one" } },
        "margin": { name: "margin", result: { "kind": "scalar", "cardinality": "one" } },
      },
    },
  },
};

// useQuery runtime entrypoint
export function useQuery(config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useGQLensSession({ ...config, schema: gqlensSchema });
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, gqlensSchema, gqlensSchema.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// useLiveQuery runtime entrypoint
export function useLiveQuery(config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useLiveGQLensSession({ ...config, schema: gqlensSchema });
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, gqlensSchema, gqlensSchema.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// usePreparedQuery prepared runtime entrypoint
export function usePreparedQuery(selection: PreparedSelection, variables: Readonly<Record<string, unknown>>, config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useGQLensSession({ ...config, schema: gqlensSchema });
  for (const path of bindGQLensSelection(selection, variables)) {
    state.demand(path.root, path.steps);
  }
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, gqlensSchema, gqlensSchema.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// Static selector builders
export function defineSelection(callback: (q: QueryNode, v: (name: string) => VariablePlaceholder) => void): PreparedSelection {
  return defineGQLensSelection<QueryNode>(gqlensSchema, gqlensSchema.query, callback);
}

export function defineInvalidation(callback: (q: QueryNode) => unknown): GraphDataInvalidation {
  return defineGQLensInvalidation<QueryNode>(gqlensSchema, gqlensSchema.query, callback);
}

// Mutation operation descriptors
export const api: {
  readonly customerHealth: {
    readonly set: MutationOperation<Types.MutationSetCustomerHealthArgs, Pick<NonNullable<Types.Mutation["setCustomerHealth"]>, "id" | "__typename" | "name" | "owner" | "tier" | "region" | "healthScore">>;
  };
  readonly mutation: {
    readonly approveOrder: MutationOperation<Types.MutationApproveOrderArgs, Pick<NonNullable<Types.Mutation["approveOrder"]>, "id" | "__typename" | "customerId" | "sku" | "status" | "amount" | "margin">>;
  };
  readonly orderAmount: {
    readonly update: MutationOperation<Types.MutationUpdateOrderAmountArgs, Pick<NonNullable<Types.Mutation["updateOrderAmount"]>, "id" | "__typename" | "customerId" | "sku" | "status" | "amount" | "margin">>;
  };
} = {
  customerHealth: {
    set: {
      operationName: "setCustomerHealth",
      query: "mutation setCustomerHealth($id: String!, $score: Float!) { setCustomerHealth(id: $id, score: $score) { id __typename name owner tier region healthScore } }",
      schema: gqlensSchema,
      variables: (input: Types.MutationSetCustomerHealthArgs): Record<string, unknown> => ({
        id: input.id,
        score: input.score,
      }),
    },
  },
  mutation: {
    approveOrder: {
      operationName: "approveOrder",
      query: "mutation approveOrder($id: String!) { approveOrder(id: $id) { id __typename customerId sku status amount margin } }",
      schema: gqlensSchema,
      variables: (input: Types.MutationApproveOrderArgs): Record<string, unknown> => ({
        id: input.id,
      }),
    },
  },
  orderAmount: {
    update: {
      operationName: "updateOrderAmount",
      query: "mutation updateOrderAmount($id: String!, $amount: Float!) { updateOrderAmount(id: $id, amount: $amount) { id __typename customerId sku status amount margin } }",
      schema: gqlensSchema,
      variables: (input: Types.MutationUpdateOrderAmountArgs): Record<string, unknown> => ({
        id: input.id,
        amount: input.amount,
      }),
    },
  },
};
