// @generated by LoaderService.buildSnapshot
// 2025-11-22T15:16:55.420Z
/* eslint-disable */


export {  };

export const registry = {} as const;
 
    export type PluginName = keyof typeof registry;
