// Auto-generated by @gqlens/codegen
// Sections: typed nodes, schema contract, runtime entrypoints, selectors, mutation API.
import { useGQLensSession, useLiveGQLensSession, type QueryConfig as GQLensQueryConfig } from "@gqlens/react";
import {
  bindSelection as bindGQLensSelection,
  createAccessorNode,
  defineInvalidation as defineGQLensInvalidation,
  defineSelection as defineGQLensSelection,
  type AccessorContext,
  type GQLensSchemaContract,
} from "@gqlens/core/codegen";
import type {
  GraphDataInvalidation,
  MutationOperation,
  PreparedSelection,
  VariablePlaceholder,
} from "@gqlens/core";
import type * as Types from "./types";

type GQLensArgValue<T> =
  T extends readonly (infer Item)[]
    ? readonly GQLensArgValue<Item>[] | VariablePlaceholder
    : T extends object
      ? { readonly [Key in keyof T]: GQLensArgValue<T[Key]> } | VariablePlaceholder
      : T | VariablePlaceholder;
type GQLensArgs<T> = { readonly [Key in keyof T]: GQLensArgValue<T[Key]> };
type GQLensQueryOptions = Omit<GQLensQueryConfig, "schema">;

// Typed accessor nodes
export interface PluginCatalogNode {
  readonly __typename: string | undefined;
  readonly plugin: (args: GQLensArgs<Types.PluginCatalogPluginArgs>) => PluginNode;
  readonly plugins: { readonly ids: readonly string[] | undefined };
  readonly status: PluginStatusOverviewNode;
  readonly group: (args: GQLensArgs<Types.PluginCatalogGroupArgs>) => PluginGroupNode;
  readonly groups: { readonly ids: readonly string[] | undefined };
}

export interface PluginStatusOverviewNode {
  readonly __typename: string | undefined;
  readonly plugins: { readonly ids: readonly string[] | undefined };
  readonly summary: PluginStatusSummaryNode;
}

export interface PluginStatusSummaryNode {
  readonly __typename: string | undefined;
  readonly total: Types.PluginStatusSummary["total"] | undefined;
  readonly running: Types.PluginStatusSummary["running"] | undefined;
  readonly stopped: Types.PluginStatusSummary["stopped"] | undefined;
  readonly disabled: Types.PluginStatusSummary["disabled"] | undefined;
}

export interface PluginGroupNode {
  readonly __typename: string | undefined;
  readonly id: Types.PluginGroup["id"] | undefined;
  readonly groupId: Types.PluginGroup["groupId"] | undefined;
  readonly name: Types.PluginGroup["name"] | undefined;
  readonly pluginIds: Types.PluginGroup["pluginIds"] | undefined;
}

export interface PluginNode {
  readonly __typename: string | undefined;
  readonly id: Types.Plugin["id"] | undefined;
  readonly name: Types.Plugin["name"] | undefined;
  readonly detail: PluginDetailNode;
  readonly status: PluginStatusNode;
}

export interface PluginDetailNode {
  readonly __typename: string | undefined;
  readonly name: Types.PluginDetail["name"] | undefined;
  readonly desc: Types.PluginDetail["desc"] | undefined;
  readonly dependencies: { readonly ids: readonly string[] | undefined };
}

export interface PluginStatusNode {
  readonly __typename: string | undefined;
  readonly isRunning: Types.PluginStatus["isRunning"] | undefined;
  readonly isEnabled: Types.PluginStatus["isEnabled"] | undefined;
  readonly lifecycleStage: Types.PluginStatus["lifecycleStage"] | undefined;
  readonly source: PluginSourceInfoNode;
}

export interface PluginSourceInfoNode {
  readonly __typename: string | undefined;
  readonly kind: Types.PluginSourceInfo["kind"] | undefined;
  readonly moduleId: Types.PluginSourceInfo["moduleId"] | undefined;
  readonly packageName: Types.PluginSourceInfo["packageName"] | undefined;
  readonly version: Types.PluginSourceInfo["version"] | undefined;
  readonly tag: Types.PluginSourceInfo["tag"] | undefined;
}

export interface PackageManagerNode {
  readonly __typename: string | undefined;
  readonly loadIssue: (args: GQLensArgs<Types.PackageManagerLoadIssueArgs>) => PackageLoadIssueNode;
  readonly loadIssues: { readonly ids: readonly string[] | undefined };
  readonly inventoryEntry: (args: GQLensArgs<Types.PackageManagerInventoryEntryArgs>) => PackageInventoryEntryNode;
  readonly inventory: (args?: GQLensArgs<Types.PackageManagerInventoryArgs>) => { readonly ids: readonly string[] | undefined };
}

export interface PackageLoadIssueNode {
  readonly __typename: string | undefined;
  readonly id: Types.PackageLoadIssue["id"] | undefined;
  readonly spec: PackageIssueSpecNode;
  readonly source: Types.PackageLoadIssue["source"] | undefined;
  readonly message: Types.PackageLoadIssue["message"] | undefined;
  readonly error: Types.PackageLoadIssue["error"] | undefined;
  readonly moduleId: Types.PackageLoadIssue["moduleId"] | undefined;
  readonly recordedAt: Types.PackageLoadIssue["recordedAt"] | undefined;
}

export interface PackageIssueSpecNode {
  readonly __typename: string | undefined;
  readonly key: Types.PackageIssueSpec["key"] | undefined;
  readonly name: Types.PackageIssueSpec["name"] | undefined;
  readonly version: Types.PackageIssueSpec["version"] | undefined;
  readonly tag: Types.PackageIssueSpec["tag"] | undefined;
  readonly target: Types.PackageIssueSpec["target"] | undefined;
  readonly raw: Types.PackageIssueSpec["raw"] | undefined;
}

export interface PackageInventoryEntryNode {
  readonly __typename: string | undefined;
  readonly id: Types.PackageInventoryEntry["id"] | undefined;
  readonly spec: PackageIssueSpecNode;
  readonly installedVersion: Types.PackageInventoryEntry["installedVersion"] | undefined;
  readonly requestedVersion: Types.PackageInventoryEntry["requestedVersion"] | undefined;
  readonly loaded: Types.PackageInventoryEntry["loaded"] | undefined;
  readonly moduleId: Types.PackageInventoryEntry["moduleId"] | undefined;
  readonly issues: { readonly ids: readonly string[] | undefined };
}

export interface QueryNode {
  readonly __typename: string | undefined;
  readonly _empty: Types.Query["_empty"] | undefined;
  readonly pluginCatalog: PluginCatalogNode;
  readonly packageManager: PackageManagerNode;
}

// Schema contract consumed by @gqlens/core
export const gqlensSchema: GQLensSchemaContract = {
  query: {
    type: "Query",
    kind: "root",
    fields: {
      "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
      "_empty": { name: "_empty", result: { "kind": "scalar", "cardinality": "one" } },
      "pluginCatalog": { name: "pluginCatalog", result: { "kind": "object", "cardinality": "one", "typeName": "PluginCatalog", "objectKind": "value" } },
      "packageManager": { name: "packageManager", result: { "kind": "object", "cardinality": "one", "typeName": "PackageManager", "objectKind": "value" } },
    },
  },
  mutation: {
    type: "Mutation",
    kind: "root",
    fields: {
      "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
      "updatePluginGroups": { name: "updatePluginGroups", result: { "kind": "object", "cardinality": "list", "typeName": "PluginGroup", "objectKind": "entity" }, args: { "groups": "[UpdatePluginGroupsGroupsInput!]!" } },
    },
  },
  objects: {
    "PluginCatalog": {
      type: "PluginCatalog",
      kind: "value",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "plugin": { name: "plugin", result: { "kind": "object", "cardinality": "one", "typeName": "Plugin", "objectKind": "entity" }, args: { "id": "String!" } },
        "plugins": { name: "plugins", result: { "kind": "object", "cardinality": "list", "typeName": "Plugin", "objectKind": "entity" } },
        "status": { name: "status", result: { "kind": "object", "cardinality": "one", "typeName": "PluginStatusOverview", "objectKind": "value" } },
        "group": { name: "group", result: { "kind": "object", "cardinality": "one", "typeName": "PluginGroup", "objectKind": "entity" }, args: { "id": "String!" } },
        "groups": { name: "groups", result: { "kind": "object", "cardinality": "list", "typeName": "PluginGroup", "objectKind": "entity" } },
      },
    },
    "PluginStatusOverview": {
      type: "PluginStatusOverview",
      kind: "value",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "plugins": { name: "plugins", result: { "kind": "object", "cardinality": "list", "typeName": "Plugin", "objectKind": "entity" } },
        "summary": { name: "summary", result: { "kind": "object", "cardinality": "one", "typeName": "PluginStatusSummary", "objectKind": "value" } },
      },
    },
    "PluginStatusSummary": {
      type: "PluginStatusSummary",
      kind: "value",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "total": { name: "total", result: { "kind": "scalar", "cardinality": "one" } },
        "running": { name: "running", result: { "kind": "scalar", "cardinality": "one" } },
        "stopped": { name: "stopped", result: { "kind": "scalar", "cardinality": "one" } },
        "disabled": { name: "disabled", result: { "kind": "scalar", "cardinality": "one" } },
      },
    },
    "PluginGroup": {
      type: "PluginGroup",
      kind: "entity",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "id": { name: "id", result: { "kind": "scalar", "cardinality": "one" } },
        "groupId": { name: "groupId", result: { "kind": "scalar", "cardinality": "one" } },
        "name": { name: "name", result: { "kind": "scalar", "cardinality": "one" } },
        "pluginIds": { name: "pluginIds", result: { "kind": "scalar", "cardinality": "list" } },
      },
    },
    "Plugin": {
      type: "Plugin",
      kind: "entity",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "id": { name: "id", result: { "kind": "scalar", "cardinality": "one" } },
        "name": { name: "name", result: { "kind": "scalar", "cardinality": "one" } },
        "detail": { name: "detail", result: { "kind": "object", "cardinality": "one", "typeName": "PluginDetail", "objectKind": "value" } },
        "status": { name: "status", result: { "kind": "object", "cardinality": "one", "typeName": "PluginStatus", "objectKind": "value" } },
      },
    },
    "PluginDetail": {
      type: "PluginDetail",
      kind: "value",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "name": { name: "name", result: { "kind": "scalar", "cardinality": "one" } },
        "desc": { name: "desc", result: { "kind": "scalar", "cardinality": "one" } },
        "dependencies": { name: "dependencies", result: { "kind": "object", "cardinality": "list", "typeName": "Plugin", "objectKind": "entity" } },
      },
    },
    "PluginStatus": {
      type: "PluginStatus",
      kind: "value",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "isRunning": { name: "isRunning", result: { "kind": "scalar", "cardinality": "one" } },
        "isEnabled": { name: "isEnabled", result: { "kind": "scalar", "cardinality": "one" } },
        "lifecycleStage": { name: "lifecycleStage", result: { "kind": "scalar", "cardinality": "one" } },
        "source": { name: "source", result: { "kind": "object", "cardinality": "one", "typeName": "PluginSourceInfo", "objectKind": "value" } },
      },
    },
    "PluginSourceInfo": {
      type: "PluginSourceInfo",
      kind: "value",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "kind": { name: "kind", result: { "kind": "scalar", "cardinality": "one" } },
        "moduleId": { name: "moduleId", result: { "kind": "scalar", "cardinality": "one" } },
        "packageName": { name: "packageName", result: { "kind": "scalar", "cardinality": "one" } },
        "version": { name: "version", result: { "kind": "scalar", "cardinality": "one" } },
        "tag": { name: "tag", result: { "kind": "scalar", "cardinality": "one" } },
      },
    },
    "PackageManager": {
      type: "PackageManager",
      kind: "value",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "loadIssue": { name: "loadIssue", result: { "kind": "object", "cardinality": "one", "typeName": "PackageLoadIssue", "objectKind": "entity" }, args: { "id": "String!" } },
        "loadIssues": { name: "loadIssues", result: { "kind": "object", "cardinality": "list", "typeName": "PackageLoadIssue", "objectKind": "entity" } },
        "inventoryEntry": { name: "inventoryEntry", result: { "kind": "object", "cardinality": "one", "typeName": "PackageInventoryEntry", "objectKind": "entity" }, args: { "id": "String!", "includeUntracked": "Boolean" } },
        "inventory": { name: "inventory", result: { "kind": "object", "cardinality": "list", "typeName": "PackageInventoryEntry", "objectKind": "entity" }, args: { "includeUntracked": "Boolean" } },
      },
    },
    "PackageLoadIssue": {
      type: "PackageLoadIssue",
      kind: "entity",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "id": { name: "id", result: { "kind": "scalar", "cardinality": "one" } },
        "spec": { name: "spec", result: { "kind": "object", "cardinality": "one", "typeName": "PackageIssueSpec", "objectKind": "value" } },
        "source": { name: "source", result: { "kind": "scalar", "cardinality": "one" } },
        "message": { name: "message", result: { "kind": "scalar", "cardinality": "one" } },
        "error": { name: "error", result: { "kind": "scalar", "cardinality": "one" } },
        "moduleId": { name: "moduleId", result: { "kind": "scalar", "cardinality": "one" } },
        "recordedAt": { name: "recordedAt", result: { "kind": "scalar", "cardinality": "one" } },
      },
    },
    "PackageIssueSpec": {
      type: "PackageIssueSpec",
      kind: "value",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "key": { name: "key", result: { "kind": "scalar", "cardinality": "one" } },
        "name": { name: "name", result: { "kind": "scalar", "cardinality": "one" } },
        "version": { name: "version", result: { "kind": "scalar", "cardinality": "one" } },
        "tag": { name: "tag", result: { "kind": "scalar", "cardinality": "one" } },
        "target": { name: "target", result: { "kind": "scalar", "cardinality": "one" } },
        "raw": { name: "raw", result: { "kind": "scalar", "cardinality": "one" } },
      },
    },
    "PackageInventoryEntry": {
      type: "PackageInventoryEntry",
      kind: "entity",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "id": { name: "id", result: { "kind": "scalar", "cardinality": "one" } },
        "spec": { name: "spec", result: { "kind": "object", "cardinality": "one", "typeName": "PackageIssueSpec", "objectKind": "value" } },
        "installedVersion": { name: "installedVersion", result: { "kind": "scalar", "cardinality": "one" } },
        "requestedVersion": { name: "requestedVersion", result: { "kind": "scalar", "cardinality": "one" } },
        "loaded": { name: "loaded", result: { "kind": "scalar", "cardinality": "one" } },
        "moduleId": { name: "moduleId", result: { "kind": "scalar", "cardinality": "one" } },
        "issues": { name: "issues", result: { "kind": "object", "cardinality": "list", "typeName": "PackageLoadIssue", "objectKind": "entity" } },
      },
    },
  },
};

// useQuery runtime entrypoint
export function useQuery(config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useGQLensSession({ ...config, schema: gqlensSchema });
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, gqlensSchema, gqlensSchema.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// useLiveQuery runtime entrypoint
export function useLiveQuery(config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useLiveGQLensSession({ ...config, schema: gqlensSchema });
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, gqlensSchema, gqlensSchema.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// usePreparedQuery prepared runtime entrypoint
export function usePreparedQuery(selection: PreparedSelection, variables: Readonly<Record<string, unknown>>, config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useGQLensSession({ ...config, schema: gqlensSchema });
  for (const path of bindGQLensSelection(selection, variables)) {
    state.demand(path.root, path.steps);
  }
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, gqlensSchema, gqlensSchema.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// Static selector builders
export function defineSelection(callback: (q: QueryNode, v: (name: string) => VariablePlaceholder) => void): PreparedSelection {
  return defineGQLensSelection<QueryNode>(gqlensSchema, gqlensSchema.query, callback);
}

export function defineInvalidation(callback: (q: QueryNode) => unknown): GraphDataInvalidation {
  return defineGQLensInvalidation<QueryNode>(gqlensSchema, gqlensSchema.query, callback);
}

// Mutation operation descriptors
export const api: {
  readonly pluginGroups: {
    readonly update: MutationOperation<Types.MutationUpdatePluginGroupsArgs, Array<Pick<NonNullable<NonNullable<Types.Mutation["updatePluginGroups"]>[number]>, "id" | "__typename" | "groupId" | "name" | "pluginIds">>>;
  };
} = {
  pluginGroups: {
    update: {
      operationName: "updatePluginGroups",
      query: "mutation updatePluginGroups($groups: [UpdatePluginGroupsGroupsInput!]!) { updatePluginGroups(groups: $groups) { id __typename groupId name pluginIds } }",
      schema: gqlensSchema,
      variables: (input: Types.MutationUpdatePluginGroupsArgs): Record<string, unknown> => ({
        groups: input.groups,
      }),
    },
  },
};
