import { writeFileSync } from 'node:fs'
import type { DiscoveredPlugin } from '@pluxel/runtime-loader/dev'
import { dirname, resolve } from 'pathe'

export const DEFAULT_LOADER_DEV_DISCOVERED_BASENAME =
	'pluxel.loader.dev.discovered.jsonc' as const

function toPosix(p: string) {
	return p.replaceAll('\\', '/')
}

function toRootRelative(rootDirAbs: string, absPath: string) {
	const root = toPosix(resolve(rootDirAbs))
	const abs = toPosix(resolve(absPath))
	if (abs === root) return '.'
	const prefix = root.endsWith('/') ? root : `${root}/`
	if (abs.startsWith(prefix)) return abs.slice(prefix.length)
	return abs
}

function uniqSorted(items: readonly string[]): string[] {
	return [...new Set(items)].sort((a, b) => a.localeCompare(b))
}

export function defaultLoaderDevDiscoveredIndexHeaderComment(): string {
	return [
		'// Generated by `pluxel dev`.',
		'// Reference-only: helps humans/LLMs edit pluxel.loader.dev.jsonc without running the CLI.',
		'// Do not edit this file manually; re-run `pluxel dev doctor` (or `pluxel dev`) to refresh.',
		'',
	].join('\n')
}

export function resolveLoaderDevDiscoveredIndexPath(configPath: string) {
	return resolve(dirname(configPath), DEFAULT_LOADER_DEV_DISCOVERED_BASENAME)
}

export function writeLoaderDevDiscoveredIndex(params: {
	rootDir: string
	configPath: string
	activeProfile: string
	rootsExpandedAbs?: string[]
	excludeGlobs?: string[]
	hiddenPackages?: string[]
	builtinPackages?: string[]
	omitFromEntries?: string[]
	discovered: DiscoveredPlugin[]
}) {
	const rootDirAbs = resolve(params.rootDir)
	const discoveredSorted = [...params.discovered].sort(
		(a, b) => a.name.localeCompare(b.name) || a.pkgDir.localeCompare(b.pkgDir),
	)

	const builtinPackages = uniqSorted((params.builtinPackages ?? []).map(String).filter(Boolean))
	const omitFromEntries = uniqSorted((params.omitFromEntries ?? []).map(String).filter(Boolean))
	const hiddenPackages = uniqSorted((params.hiddenPackages ?? []).map(String).filter(Boolean))

	const discoveredNames = uniqSorted(discoveredSorted.map((p) => p.name))
	const enabledCandidates = discoveredNames.filter((n) => !builtinPackages.includes(n))

	const rootsExpanded = params.rootsExpandedAbs?.length
		? params.rootsExpandedAbs.map((abs) => toRootRelative(rootDirAbs, abs))
		: undefined

	const payload = {
		generatedAt: new Date().toISOString(),
		config: {
			path: toRootRelative(rootDirAbs, params.configPath),
			activeProfile: params.activeProfile,
		},
		workspace: {
			...(rootsExpanded ? { rootsExpanded } : {}),
			...(params.excludeGlobs?.length ? { excludeGlobs: [...params.excludeGlobs] } : {}),
			...(hiddenPackages.length > 0 ? { hiddenPackages } : {}),
		},
		builtin: {
			...(builtinPackages.length > 0 ? { packages: builtinPackages } : {}),
			...(omitFromEntries.length > 0 ? { omitFromEntries } : {}),
		},
		discovered: {
			count: discoveredSorted.length,
			packageNames: discoveredNames,
			enabledCandidates,
			pluginPackages: discoveredSorted.map((p) => ({
				name: p.name,
				pkgDir: p.pkgDir,
				entry: p.entry,
			})),
		},
	}

	const outPath = resolveLoaderDevDiscoveredIndexPath(params.configPath)
	const header = defaultLoaderDevDiscoveredIndexHeaderComment()
	const json = JSON.stringify(payload, null, '\t')
	writeFileSync(outPath, `${header}${json}\n`, 'utf8')
}
