// packages/components/src/extension/types.ts

export {
	type AnyExtensionDef,
	type BuiltinExtensionBase,
	type BuiltinExtensionDef,
	type BuiltinExtensionKind,
	type BuiltinBadgeValue,
	type BuiltinDocBlock,
	type BuiltinDocBlockKind,
	type BuiltinDocContent,
	type BuiltinDocExtensionDef,
	type BuiltinDocPart,
	type BuiltinInfoCardBlock,
	type BuiltinInfoCardLayout,
	type BuiltinInfoCardRow,
	type BuiltinRpcArg,
	type BuiltinRpcAutoFormBlock,
	type BuiltinSseRef,
	type BuiltinValue,
	type CompiledExtensionModule,
	createGlobalExtensionContext,
	createPluginExtensionContext,
	type ExtensionContext,
	type ExtensionDef,
	type ExtensionItem,
	type ExtensionManifest,
	type ExtensionManifestEvent,
	type ExtensionMeta,
	type ExtensionPoint,
	type ExtensionPointCtx,
	type ExtensionPointMap,
	type ExtensionPointMeta,
	ExtensionProvider,
	ExtensionPoints,
	type GlobalExtensionContext,
	isExtensionPluginRunning,
	doc,
	type PluginExtensionContext,
	type PluginUIModule,
	type RouteExtensionDef,
	toGlobalExtensionContext,
	type UiConfirmPayload,
	type UiConfirmTone,
	type UiNotifyPayload,
	type UiNotifyTone,
	type ExtensionProviderProps,
	useExtensionContext,
} from '@pluxel/runtime/web'
