name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

env:
  CI: 'true'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup toolchain
        uses: ./.github/actions/setup-toolchain

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpm -r publish --access public --no-git-checks --provenance
